import type { TextCollection } from '../types';

export const fiveyearoldTexts: TextCollection = {
    short: [
        // 100 KORTE TEKSTER (30–80 tegn, barnlig begeistring, 1 setning)
        "Se, en marihøne på fingeren min! Den kiler meg litt!",
        "Hvorfor er regndråper så våte og fulle av plask?",
        "Jeg hoppet så høyt i stad at jeg nesten traff en sky!",
        "Kan hunder drømme om rosa dinosaurer, tro?",
        "Sjiraffer må ha veldig lange skjerf om vinteren!",
        "Hør, jeg lager en sang med bare surr og tulleord!",
        "Er is og godteri en bra frokost, eller blir man klissete?",
        "Hvorfor er pærer så rare, men smaker så godt?",
        "Kan jeg klatre i taket hvis jeg har superlim på tærne?",
        "Jeg så en sky som ligna en sprø sjokolade i dag!",
        "Tenk om jeg kunne kjøre sparkesykkel på månen!",
        "Hvorfor kiler det i magen når jeg svinger rundt?",
        "Jeg lagde en hytte av tepper, nå bor jeg i en hule!",
        "En gang drømte jeg at jeg var en oransje elefant!",
        "Hør, jeg hvisker kjempehøyt: HVISK HVISK HVISK!",
        "Kan en kanin ha på seg sokker og hoppe enda høyere?",
        "Jeg vil tegne en regnbue med hundre farger i dag!",
        "Et tre er jo egentlig en kjempestor pinne med blader!",
        "Hvorfor kan ikke jeg ha hale så jeg kan vifte med den?",
        "Mamma sier jeg er en rakett når jeg løper fort!",
        "Jeg lurer på hva edderkopper gjør når de kjeder seg!",
        "Kan en bil spise gress hvis den er veldig sulten?",
        "Se på håret mitt, det er like bustete som en løve!",
        "I dag skal jeg bare tegne sola med glade solbriller!",
        "Har du smakt en sky? Den ser ut som søt sukkerspinn!",
        "Hvis jeg skriker, hører månen meg da, tro?",
        "Kan jeg fly hvis jeg vifter armene skikkelig fort?",
        "Jeg fant en kjempelang mark og kalte den for Mark!",
        "En gang hoppet jeg fem ganger, da ble jeg svimmel!",
        "Pappa sier at jeg er en zombizombie når jeg er trøtt!",
        "Hvorfor smelter isen så fort når jeg ser på den?",
        "Kan fugler egentlig kose med hverandre i lufta?",
        "Jeg malte fingrene mine grønne, nå er jeg en plante!",
        "Tenk om jeg kunne bo på en sky og se ned på alt!",
        "Hvorfor roper jeg alltid «au» før jeg slår meg, tro?",
        "Jeg så en marihøne med seks prikker, den var kul!",
        "Kan jeg klappe en stjerne eller er den for varm?",
        "Jeg vil ha superkrefter og fly til en magisk zoo!",
        "Se, jeg tegnet en bil som kjører på en regnbuevei!",
        "Hvorfor har ikke jeg kjempekorte bein som en and?",
        "Jeg prøvde å slikke albuen min, men det gikk ikke!",
        "Pinnsvin ser ut som levende kaktuser, er ikke det rart?",
        "Jeg liker å puste på vinduet for å tegne med tåka!",
        "Kan babyer lage rare monsterlyder i søvne?",
        "En ballong kan reise helt til rommet hvis den får bli fri!",
        "Hvorfor kan jeg ikke spise dessert før middagen?",
        "Jeg ropte «bæsj» i barnehagen, og alle bare lo!",
        "Hva hvis jeg snurrer rundt til jeg blir en tornado?",
        "Jeg klippet papiret i tusen biter, nå er det konfetti!",
        "Kan trær føle at det blåser på dem, mon tro?",
        "Hør, knærne mine lager en morsom lyd når jeg bøyer dem!",
        "Hvor mange hoppetau-hopp kan jeg klare i søvne?",
        "Se, jeg fant en snegle! Den har hus, men ingen dør!",
        "Hahaha, jeg kan tegne en sol på nesa di med en tusj!",
        "Hvorfor smaker tannkremen som peppermynte-is?",
        "Tenk om jeg hadde vinger på føttene, jeg ville løpt flyvende!",
        "Jeg så en sky som smilte til meg i sted, helt sant!",
        "Kan jeg lage en bursdagskake av bare pinner og blader?",
        "Se på magen min, den rumler som en sint liten tiger!",
        "Hvis jeg vrir tunga rart, lager jeg en rar pipelyd!",
        "En fotball er rund, men en banan er buet, hihi!",
        "Jeg vil danse og synge som en høne som vifter vingene!",
        "Hvorfor sildrer vannet sånn når jeg drar i krana?",
        "Jeg er kjempesterk, jeg løftet en stein som veide to tonn!",
        "Papir flyr bra, men saksen blir bare liggende på bakken!",
        "Hør, jeg laget en hemmelig språk: bibi-bubu-lala!",
        "Tenk om skyggen min er en venn som følger meg alltid!",
        "Kan jeg male tennene mine blå og late som jeg er et spøkelse?",
        "Jeg har en sang i hodet: dum-di-dum-di-dum!",
        "Hvorfor vokser det ikke frukt på snøen om vinteren?",
        "Se, jeg hopper på én fot mens jeg teller til femti!",
        "Hadde jeg hatt en hale, skulle jeg hengt meg opp i trær!",
        "Jeg lagde et ansikt av agurk på brødskiva mi!",
        "Kan pingviner og isbjørner bli bestevenner?",
        "Hør, jeg roper skikkelig høyt: HALLOOO HELE VERDEN!",
        "Hvorfor kan ikke jeg sove oppå skyene i natt?",
        "Jeg tegnet en drage med tjue hoder og ti haler!",
        "Kjolen min snurrer som en karusell når jeg danser!",
        "Kan et marsvin dra på ferie i en koffert, tro?",
        "Jeg lurer på hvorfor poteter ikke kan være grønne?",
        "Tenk om jeg kunne fange en meteor med hånda mi!",
        "Du, jeg så en liten mus under benken, den pep søtt!",
        "Hvorfor lukter nesen min ingenting når jeg klyper den?",
        "Jeg trodde en edderkopp var en liten ninja!",
        "Kan en sitron smile hvis den får et ansikt tegnet på?",
        "Jeg elsker å grise med vann, plask plask!",
        "Hvorfor smaker kylling nuggetene bedre på tur?",
        "Jeg vil klatre på et fjell og rope: JEG ER EN FJELLAPEE!",
        "Se, jeg fant en stein som ligner på et lite troll!",
        "Kan en ball bli sliten hvis jeg sparker den for hardt?",
        "Pappa sier jeg snakker så mye at munnen min trenger ferie!",
        "Jeg prøvde å fange en frosk, men den hoppet bare vekk!",
        "Hvorfor svømmer ikke gresshopper i badekaret mitt?",
        "Jeg elsker ketchup, det er som en rød maltedrikk!",
        "Et spøkelse er kanskje bare en lur sky i rommet!",
        "Kan jeg bygge et slott av fluffete puter og bamser?",
        "Å snyte nesa er ekkelt, men det er litt gøy også!",
        "Jeg lukket øynene og så mange rare farger inni hodet!",
        "Hvorfor sover tigre aldri i sengen min, tro?",
        "Jeg vil male en astronaut som spiser pannekaker!",
        "Hør, jeg er en trompet: prutt-pruutt-praaa!",
        "Hvorfor blir jeg våt i håret når det regner, men ikke i munnen?",
        "Jeg vil at alle sommerfugler skal bli vennene mine!",
        "Se, jeg kan løpe baklengs mens jeg roper ABC!",
        "Kan man skrive en bok uten bokstaver, bare tegninger?",
        "Jeg spiste en skive med honning, og tunga mi kribler enda!",
        "Hvorfor kan ikke jeg skifte farge på øynene hver dag?",
        "Jeg tegnet en katt med rund snute og firkantede ører!",
        "Tenk om jeg hadde lomme i magen, akkurat som en kenguru!",
        "Jeg vil danse i regnet og fange dråper med håret!"
    ],
    medium: [
        // 100 MELLOMLANGE TEKSTER (2–3 setninger, 150–250 tegn, barnlig engasjement)
        "I dag fant jeg en bitte liten bille under en stein, og den var helt svart og blank. Jeg prøvde å lage hus til den av pinner og blader. Så ble den borte, men kanskje den kommer tilbake i morgen!",
        "Har du noen gang sett en regnbue som begynner i nabohagen? Jeg tror det finnes en magisk skatt der, men jeg må finne et kart først. Kanskje jeg lager et selv med kjempefine tegninger!",
        "Da jeg våknet, var jeg sikker på at jeg hadde fått superkrefter i tærne. Men det viste seg at jeg bare hadde sovet med sokkene feil vei. Det var likevel litt morsomt å tro det en stund!",
        "Jeg sang en sang til katten min som bare var mjau og pipelyder. Den så litt forvirra ut, men så la den seg på ryggen. Kanskje den likte konserten min likevel!",
        "Pappa sa jeg skulle rydde rommet, men jeg fant heller opp et helt nytt eventyr inni skapet. Så ble alt enda mer rotete, men det var gøy. Kanskje jeg kan bli eventyrforfatter når jeg blir stor!",
        "Visste du at jeg kan bære tre bamser samtidig mens jeg synger? Jeg øver på å balansere dem på hodet også, men da falt de ned. Mamma bare lo og sa jeg hadde en rar oppfinnelse!",
        "Jeg hørte en fugl som sang i dag, og jeg prøvde å synge akkurat likt. Kanskje den skjønte at jeg hermet, for den fløy sin vei. Men jeg skal øve, så vi kan bli duett-partnere!",
        "Har du smakt blomster før? Jeg fant noen spiselige i hagen, men de smakte ikke akkurat kake. Likevel følte jeg meg litt som en humle da jeg spiste dem!",
        "I dag prøvde jeg å tegne en hel by med tusj, men halvveis kom jeg på at jeg måtte spise lunsj. Da jeg kom tilbake, hadde tusjen tørket ut litt. Kanskje byen min ble ekstra fin med litt spraglete farge!",
        "Jeg drømte om en kjempeveps som sa hei på et rart språk. Da jeg våknet, trodde jeg den fulgte etter meg rundt i huset. Men det var visst bare søsteren min som buzzet for å erte meg!",
        "Kan man lære en fisk å kaste ball? Jeg har tenkt å prøve, men jeg må finne en fisk med hender. Kanskje jeg bare må tegne en fisk med hender i stedet!",
        "En dag skal jeg bli oppfinner av godteri som aldri tar slutt. Mamma sa det var litt mye sukker, men jeg kan sikkert putte litt grønt i det. Da smaker det vel likevel søtt og sunt!",
        "Jeg så meg selv i speilet og prøvde å se ut som en løve. Jeg ristet på håret og brølte litt for å øve. Kanskje jeg overrasker noen i barnehagen med løvebrøl i morgen!",
        "I dag la jeg en liten bamse inni en eske og kalte det bamsens hus. Jeg ga den en eplebit, men den ble litt klissete. Nå må jeg vaske bamse-huset før mamma ser det!",
        "Jeg fikk en sjokoladebit og prøvde å spare den hele dagen. Men den ropte på meg, og plutselig var den borte i magen min. Jeg tror sjokolade ikke liker å vente så lenge!",
        "Når jeg blir stor, vil jeg kjøre en rosa buss med glitregardiner. Da kan alle vennene mine bli med på tur til fantasilandet. Vi skal spille høy musikk og spise kjeks hele veien!",
        "Jeg hoppet opp på en stol og ropte at jeg var en ekte astronaut. Så prøvde jeg å telle ned fra ti, men glemte tallet fem. Likevel føltes det som jeg fløy til månen en liten stund!",
        "Kan jeg bruke en sommerfugl som hårpynt, eller blir den trist? Jeg tipper den heller vil fly rundt og samle nektar. Jeg kunne brukt en tegne-sommerfugl, det er nok mer rettferdig!",
        "Jeg pleide å tro at månen var en stor ost man kunne spise. Men mamma sa den er av stein, så jeg ble litt skuffa. Kanskje den osten finnes et annet sted i universet!",
        "I dag skreiv jeg navnet mitt baklengs og ble ganske forvirra. Kanskje jeg oppfant et nytt alfabet! Pappa skjønte ingenting da jeg viste ham det.",
        "Se, jeg kan telle til ti mens jeg står på én fot og klør meg i øret! Jeg blir litt rar i stemmen av det, men det er verdt et forsøk. Kanskje jeg kan bli akrobatiker med rare talenter.",
        "Noen ganger later jeg som at jeg er et lite monster som elsker gulrøtter. Da lager jeg monsterlyder og knasker i vei. Kan hende gulrøtter smaker bedre når man er monster?",
        "Jeg prøvde å hviske en hemmelighet til en blomst i dag. Den hørte kanskje ingenting, men jeg tror den ble glad. Blomster trenger kanskje hemmeligheter, de også!",
        "Visste du at jeg kan tegne en båt som kan kjøre i himmelen? Den har vinger og kan fly over skyer. Jeg skal reise jorda rundt med den når jeg blir stor!",
        "Jeg hadde nesten glemt at jeg la en kjeks i lomma mi i går. Nå var den helt smuldrete, men jeg spiste den likevel. Det knaste litt ekstra rart, men det var fortsatt kjeks!",
        "Hvem bestemte at vann er vått og ikke tørt? Jeg tror noen bare fant det på for lenge siden. Hvis jeg blåser på vannet, blir det vel litt tørt, eller hva?",
        "Jeg la en stein på hodet og prøvde å balansere den, men den falt ned på tåa mi. Det var skikkelig vondt, men så lo jeg fordi jeg følte meg dum. Neste gang bruker jeg en myk stein!",
        "Når jeg synger, tror jeg at fuglene svarer meg med sang. Kanskje de bare sier “bli stille”, men jeg tror de liker meg. Jeg kan late som vi har en duettkonsert!",
        "Jeg elsker lukta av nystekt brød, det kiler i nesa og magen min blir glad. Noen ganger vil jeg bare klemme brødet, men da sier mamma nei. Brødet vil jo spises, ikke klemmes!",
        "Kan jeg tegne om kvelden, selv om lyset er slukket? Mamma sier jeg trenger lys, men jeg vil bruke fantasi-øyne. Det kan funke, eller så tegner jeg bare en stor sort flekk!",
        "I dag så jeg et ekorn klatre i et tre med en nøtt i munnen. Jeg lurte på om den skulle ha nøttefest med vennene sine. Kanskje jeg burde lage en plakat: Velkommen til nøttefest!",
        "Jeg pratet så mye i bilen at pappa ba meg ta en liten pause. Da hvisket jeg bare i stedet for å snakke høyt. Men jeg tror han hørte meg likevel, hihi!",
        "Hvorfor sier vi “takk for maten” når vi er ferdige, og ikke når vi begynner? Jeg er jo sulten ved start, men mett etterpå. Kanskje jeg skal si “takk for den tomme tallerkenen” i stedet?",
        "Jeg prøvde å plukke opp en meitemark, men den var så slimete at jeg ropte litt. Så ble jeg egentlig nysgjerrig, for den er jo ganske søt med alle bevegelsene sine. Kanskje den også ropte litt inni seg.",
        "Av og til tenker jeg at tærne mine er små spioner. De lister seg rundt i sokkene uten at jeg merker det. Kanskje de rapporterer alt jeg gjør til de andre tærne?",
        "Jeg vil skape en hel verden av kritttegninger på asfalten. Så kan alle bilene kjøre i mine regnbuer og rare rundinger. Det blir den fineste byen i hele nabolaget!",
        "Mamma sier jeg spiser for mye sjokolade, men sjokolade sier ikke noe. Den bare smelter i munnen min og smiler på en måte. Kanskje jeg burde spørre sjokoladen hva den mener.",
        "Jeg hadde på meg pysjen hele formiddagen i dag, og det var helt supert. Følte meg som en koselig bamse. Kanskje jeg skal ha pysj på i barnehagen også en dag!",
        "Har du kjent på å ha en kald is i hånda så lenge at fingrene nesten fryser? Da løper jeg rundt og skriker litt før jeg spiser isen. Det er en skikkelig merkelig følelse!",
        "Noen ganger vil jeg at kattene våre skal snakke menneskespråk. Da kunne jeg fortalt dem mine største hemmeligheter. Men de sier bare “mjau” og vil kose i stedet.",
        "Visste du at jeg kan telle til tjue på fingrene mine? Jeg tar tærne med når jeg går tom for fingre. Litt vanskelig i sko, men ingenting er umulig når man prøver hardt!",
        "Jeg spilte fotball mot meg selv i hagen, og jeg vant og tapte på samme tid. Det var ganske rart å juble og være sur samtidig. Kanskje jeg må finne en ekte motspiller!",
        "I dag danset jeg som en tullete elefant rundt stuebordet. Mamma lo så hun nesten falt av stolen. Jeg tror jeg skal danse enda mer i morgen!",
        "Jeg lagde et monster av tannkremen på tannbørsten min. Det så skummelt ut, men så pusset jeg det bort. Monsteret smakte mint, og det var ganske greit!",
        "Har du noen gang kilt deg selv under foten? Det føles rart, men jeg klarer ikke helt å le av det. Jeg er litt forberedt på kilingen, tror jeg.",
        "Jeg bygger et tårn av LEGO som skal rekke helt opp til lampa. Hvis det rister litt, kan alt dette ramle ned. Det blir enten kjempekult eller kjempeuheldig!",
        "En stor hund bjeffet på meg i dag, og jeg bjeffet faktisk tilbake. Den så forvirret ut før den løp videre. Kanskje jeg snakket hundespråket riktig!",
        "Hvorfor blir himmelen oransje noen kvelder? Jeg tror den har kledd seg ut for en bursdagsfest der oppe. Kanskje skyene feirer et eller annet spennende.",
        "Jeg lagde en lang kjede av papir og trodde den var uendelig. Men plutselig var papiret slutt. Kanskje jeg trenger en magisk pappeske som aldri tar slutt?",
        "Noen sier det bor et lite monster under senga, men jeg tror det er en kanin. Jeg la en gulrot der for å se. Hvis den blir borte, er det sikkert en sulten kaninmonster!",
        "Jeg skrev navnet mitt på en lapp, men bokstavene ville ikke se rette ut. De ble som dansende klumper. Kanskje navnet mitt liker å danse på papiret?",
        "I dag smakte jeg syltetøy rett fra skjea, og tunga mi ropte “mer, mer!” Det var jordbær med litt klumper, men de klumpene smakte ekstra godt. Jeg følte meg som en syltetøypirat!",
        "Hvorfor heter det å være mørkeredd, men ikke lysredd? Jeg er ikke redd for lys, men kanskje noen er det. Sola kan jo bli ganske skarp i øynene!",
        "Jeg fikk et sugerør som var bøyd, og så var det mye morsommere å drikke. Jeg prøvde å blåse bobler, men da sølte jeg litt. Boblelyden var verdt sølet!",
        "Hvis jeg var en ridder, ville jeg ri på en skilpadde. Den går sakte, men da får jeg tid til å se meg rundt. Kanskje fiendene sovner mens jeg nærmer meg!",
        "Jeg plasserte en myk pute på gulvet for å teste om jeg kunne fly ned fra sofaen. Jeg falt som en sekk poteter, men det var ganske gøy likevel. Jeg ropte “jeg flyr” og landet pang!",
        "En bie summet rundt hodet mitt, så jeg summet tilbake. Den fløy videre, så jeg tror den ikke forstod at jeg ville bli venn. Kanskje jeg må lære bedre biespråk.",
        "Noen ganger er jeg bare så glad at jeg snurrer rundt meg selv fem ganger. Da blir jeg litt svimmel, men det er en fin måte å juble på. Hode mitt roper “hurra”!",
        "Hvis jeg var en robot, skulle jeg ha en stor knapp på magen som skiftet farge. Da kunne jeg vise hvordan jeg føler meg. Kanskje blå for trøtt og rød for superglad!",
        "Jeg så en edderkopp hoppe, og da tenkte jeg “wow, er du en gresshoppe kanskje?” Den svarte ikke, men jeg tror den ble litt stolt. Edderkopper kan sikkert gjøre mange triks!",
        "Hver gang jeg klør meg på nesa, kiler det i øyet mitt. Det er så rart, som om nesen og øyet har en hemmelig avtale. Kanskje de tuller med meg.",
        "Jeg prøvde å spise tomaten som en eple, men den var så glatt at den smatt ut av hendene. Da rullet den over gulvet som en rød ball. Nå er tomatgolvet litt sølete.",
        "Visste du at jeg kan lukke det ene øyet og se dobbelt av deg? Da ser du ut som to personer. Det er skikkelig gøy helt til jeg blir sulten!",
        "En gang mistet jeg en tann, og jeg la den under puta. Morgenen etter fikk jeg en mynt, men jeg savnet tanna litt. Det er rart å se seg i speilet med et lite hull!",
        "Jeg tror egentlig at klesvask er et magisk prosjekt, klærne snurrer rundt i vaskemaskinen som i en snøstorm. Hadde jeg passet, ville jeg også tatt en snurretur. Men mamma sier nei.",
        "Da jeg var liten, trodde jeg at alle folk ble født med ei lue på hodet. Så skjønte jeg at det bare var babylua. Litt rart at vi ikke bare har hår med en gang, egentlig!",
        "Jeg skrudde på en lommelykt i mørket og latet som jeg var en trollmann. Lysstrålen var tryllestaven min! Jeg ropte “hokus pokus” og pekte på en stol, men den ble ikke til en kanin.",
        "Noen ganger vil jeg bo i et digert slott med tusen rom og en rutsjebane fra tårnet. Men da tenker jeg at jeg kanskje hadde rotet meg helt bort. Kanskje tre rom er nok.",
        "Jeg spiste en banan og latet som den var en telefon. Jeg sa “Hallo, apekatt?” Men ingen svarte, så jeg tok en bit. Telefonen ble borte i magen min, haha!",
        "Hvorfor sier man ‘ta en lur’, kan man virkelig plukke den opp? Jeg så for meg at jeg kunne putte luren i en boks. Men en lur er vel bare å sove litt, da!",
        "Jeg fyller vann i bøtta og heller den ut, igjen og igjen. Det er som et lite fossefall i hagen. Jeg roper “plask!” og forestiller meg at jeg er ved en gigantisk foss!",
        "Jeg så en maur som bar et frø, og den så veldig sterk ut. Jeg prøvde å hjelpe, men den løp i ring. Kanskje den ikke ville ha hjelp av en kjempestor femåring?",
        "Jeg kledde på meg tre gensere i dag og følte meg som en stor marshmallow. Så ble jeg altfor varm og måtte ta dem av igjen. Men det var gøy å se ut som en pølse!",
        "Hvis jeg maler et ansikt på en fotball, blir den da levende? Jeg kommer kanskje til å sparke den i ansiktet, og det er litt slemt. Så jeg maler heller en sol, den liker sikkert spark!",
        "Hvorfor kaller vi det barnebursdag, men ikke voksebursdag? Kanskje voksne ikke vil feire så mye. Jeg vil ha bursdag hver dag, med ballonger og kake!",
        "Av og til føler jeg at jeg kan smake på lufta, spesielt når den lukter bål. Den smaker litt røykt, men jeg liker den. Det er som grillmat for nesen min!",
        "Jeg stakk fingeren i jorda for å finne marker, men fant bare en liten rot. Den så ut som en krokodillehale. Kanskje jeg kan lage en hel krokodille om jeg graver mer?",
        "Jeg prøvde å danse stille, men beina mine laget dunkelyder. Så prøvde jeg å danse høyt, men da trodde mamma jeg veltet noe. Kanskje jeg burde danse i hagen i stedet!",
        "En venn i barnehagen sa at spøkelser spiser gress. Det hørtes litt sprøtt ut, men jeg later som det er sant. Da kan jeg kanskje lokke et spøkelse fram med litt salat!",
        "Jeg fant en knapp på gulvet, og nå tror jeg det er en forsvunnet knapp fra en magisk frakk. Hvis jeg finner frakken, kan jeg kanskje bli usynlig. Jeg holder øynene åpne!",
        "Hvorfor er ikke tyggis en frukt? Den smaker jo jordbær og bringebær noen ganger. Kanskje den er en frukt i tyggelandet!",
        "Når jeg ser på film, vil jeg helst være med i filmen selv. Jeg roper til skjermen: ‘Hei, vent på meg!’ Men de hører visst ikke hva jeg sier.",
        "Jeg liker å lukte på alt mulig rart, også ting som lukter vondt. Mamma sier jeg er en liten snuser. Jeg synes lukter er som eventyr for nesa!",
        "En dag skal jeg telle alle trærne i en skog. Men da må jeg ha masse mat med meg, for det tar nok en hel uke. Kanskje jeg blir skogs-ekspert!",
        "Kan jeg lage en ny planet av leire og kalle den Smuleplaneten? Da bor det bare smuler der, som kanskje prater sammen. Jeg lurer på hva de spiser, kanskje store brød?",
        "Jeg samlet steiner i en boks og trodde det var gull. Men mamma sa det bare var vanlige steiner. Jeg kaller dem likevel for gullsteinene mine!",
        "I dag løp jeg med sokker ute, og gresset kilte meg så mye at jeg hylte. Det var verdens morsomste kiling. Jeg ble nesten som en glad hylende apekatt!",
        "Kanskje regndråpene er små vesener som bare lever i lufta en stund. Jeg kunne nesten se små ansikt på dem før de traff bakken. Da forsvant de, stakkars vesener!",
        "Jeg lagde et kart over hagen, der jeg tegnet et kryss ved en stor stein. Pappa gravde der og fant ingenting. Da sa jeg at skatten sikkert var usynlig!",
        "Hva om trærne egentlig forteller vitser til hverandre i vinden? De rasler kanskje av latter. Jeg skulle ønske jeg forsto tre-språk!",
        "Da jeg gikk til barnehagen, tenkte jeg på om jeg kunne suge opp en sky med et sugerør. Men skyene var for høyt oppe, og mamma sa jeg bare skulle gå pent videre. Jeg får vente til jeg blir høyere!",
        "Jeg snek meg inn på kjøkkenet for å spise en kakebit, men kakeboksen var tom. Kanskje kakemonsteret allerede var på besøk. Eller så spiste jeg den selv i går, hmm!",
        "Kan jeg mate en krokodille med gulrøtter hvis den er vegetarianer? Det hadde vært kult, men litt skummelt. Jeg tror ikke jeg tør å prøve hvis jeg møter en ekte krokodille!",
        "Hvorfor heter det tegneark når det kunne hete papirbit? Jeg skal kalle det maleark, for jeg malte masse farger på det i stedet for å tegne. Papiret protesterte ikke!",
        "Noen ganger vil jeg rope ut vinduet: ‘Hvem vil leke med meg?’ Men mamma sier jeg heller kan ringe en venn. Det er ikke like dramatisk, da!",
        "Jeg klatret i et tre og følte meg som en liten apekatt. Så hørte jeg grenene knirke, og da sprang jeg ned. Man vil jo ikke falle og få rumpa full av kvister!",
        "I går trodde jeg at jeg så en liten fe i blomsterbedet. Den var borte da jeg løp bort for å si hei. Kanskje den er sjenerert, eller så var det bare en bitteliten sommerfugl.",
        "Hvorfor kan jeg ikke tegne streker helt rette? De løper liksom ut av linjalen. Kanskje streker også vil være fri og vakle litt hit og dit!",
        "Jeg vil ha en kjempekasse med glitter og klistremerker, så jeg kan gjøre alt jeg eier skinnende. Mamma liker ikke glitter overalt, men jeg synes det er en magisk idé!",
        "Tenk om jeg plantet en tyggegummitre i hagen og kunne plukke rosa tyggegummi rett fra greina. Jeg måtte bare passe meg så jeg ikke sitter fast i det selv!",
        "Mamma sier at stjerner bare er brennende gasskuler, men jeg synes de ser koselige ut. Kanskje de bare kler seg i glitrende gasstøy. Jeg velger å tro det.",
        "Jeg prøvde å sykle med sko på feil fot, men det ble ganske klønete. Pappa bare ristet på hodet og lo. Jeg syntes det var et fint eksperiment!",
        "En kolibri kan visst flakse kjempefort med vingene. Jeg prøvde å gjøre det med armene, men jeg ble bare sliten. Kanskje jeg trenger treningsprogram for å bli kolibri.",
        "Når jeg åpner munnen, kan jeg se tunga bevege seg rart. Jeg tror den har eget liv der inne. Kanskje den synger en liten sang jeg ikke kan høre.",
        "Jeg ropte til en maur: ‘Halla, lille fyr!’ Den stakk av, men kanskje den egentlig sa ‘hei’ på maurspråket. Jeg liker å tro det!",
        "Jeg bygde en liten mur av klosser og kalte det et slott. Så kom en ball rullende og ødela alt. Jeg ropte ‘jordskjelv!’ og begynte å bygge på nytt!",
        "Jeg liker lukta av bensin, men mamma sier den er farlig. Jeg tror den luktet litt spenning, akkurat som før en berg-og-dalbane-tur. Men jeg sniffer ikke mer, altså!",
        "Hvorfor heter det penn og ikke bare ‘fargepinn’? Den lager jo farger eller streker. Kanskje jeg skal lage en ny ting som heter fargepinn!",
        "Jeg prøvde å si hele alfabetet baklengs, men hjernen min knøt seg i en krøll. Jeg tror bokstavene rømte da jeg kom til X. Neste gang må jeg trene litt mer!",
        "I kveld lurer jeg på om jeg kan se en stjerne falle rett i fanget mitt. Da skulle jeg ønske meg en gigantisk sjokoladefontene. Eller kanskje en kattunge i regnbuefarger!",
        "Jeg kastet opp en ball i lufta fem ganger, og den landet i hodet mitt tre av dem. Kanskje ballen elsket hodet mitt. Eller så var jeg bare dårlig til å fange.",
        "Noen ganger later jeg som jeg har en usynlig venn som heter Bobbi. Bobbi elsker å danse midt på gulvet. Mamma blir litt forvirra når jeg ler av ingen ting!",
        "Kanskje jeg kan lære en elefant å sykle? Det blir nok litt vanskelig å finne en sykkel i riktig størrelse. Men tenk så gøy hvis det gikk!",
        "Søsteren min tar så lang tid på badet, jeg tror hun er en havfrue. Kanskje hun bader i et hemmelig hav der inne. Jeg skulle ønske hun ble ferdig så jeg kan pusse tennene!",
        "I dag prøvde jeg å tegne regndråper, men de så ut som små spøkelser. Jeg ga dem øyne, og da ble de plutselig glade dråpespøkelser. De fikk bo i en tegnet sky!",
        "Når jeg blir sliten av å leke, legger jeg meg rett ned på gulvet. Gulvet er egentlig mykt hvis man legger hodet på en pute først. Jeg kaller det gulvhvile.",
        "Jeg ønsket meg en ekte alv til jul, men mamma sa de ikke finnes i butikker. Kanskje jeg må lage en selv av glanspapir og lim. Den kan bo i juletreet!",
        "Noen ganger prøver jeg å prate som en baby, men det høres bare rart ut. Babyer har en hemmelig måte å si ‘gå-gaga-bu’ på. Jeg forstår dem ikke så godt, men det er litt moro!",
        "Hvorfor sier folk ‘du må ikke spise snø’? Den ser jo så ren og fin ut. Men jeg har smakt litt, og det var som kaldt vann, men litt skittent kanskje!",
        "Jeg lekte innendørs fotball med en myk ball, men så knuste jeg en plantevase. Det var ingen som så det skje, men vasen ropte nesten ‘au!’ før den traff gulvet. Nå må jeg si unnskyld til mamma.",
        "Da jeg fant et gammelt kosedyr i skapet, klemte jeg det så hardt at øret nesten falt av. Jeg sa unnskyld til kosedyret, og nå er vi bestevenner igjen. Det fikk plaster på øret!",
        "Jeg så en reklame for en leke jeg MÅ ha, men mamma sier jeg har nok leker. Jeg tenker at jeg kanskje kan bytte en gammel en med en ny en. Mamma bare ristet på hodet.",
        "Noen ganger føles det som at beina mine kan løpe av seg selv. Jeg bare lar dem gå, og plutselig snubler jeg. Men jeg pleier å le av det, for det ser sikkert komisk ut!",
        "Å leke med dokker er ganske morsomt, men jeg gir dem alltid nye navn hver gang. Ingen av dem husker hva de het før. Det er litt forvirrende for dem, tror jeg!",
        "Jeg pleide å tro at hjernen var som en myk bamse inne i hodet. Nå vet jeg den er viktig, men jeg liker fortsatt å tenke på den som en kosebamse. Den hjelper meg å tenke snille tanker!",
        "Hvis jeg kunne endre en ting i verden, ville det være å lage en lov om at alle får dessert etter middag hver dag. Mamma sier jeg må være statsminister for det. Jeg sier: OK, jeg blir det!",
        "Har du noen gang kjent at du klør i øret når du drikker vann? Kroppen min er full av rare ledninger som gjør alt mulig rart. Jeg synes det er ganske morsomt!",
        "Jeg ropte ‘god morgen, verden’ da jeg sto opp, og hele huset våknet. Mamma og pappa var ikke like glade som meg, men de smilte litt senere. Jeg tror morgenstemminga er smittsom!",
        "Noen ganger vil jeg bare hoppe i sofaen hele dagen. Men da roper mamma ‘nei, sofaen er ikke en trampoline!’ Jeg skjønner ikke helt forskjellen, egentlig.",
        "Jeg lagde en liten båt av papir og satte den i en søledam. Den seilte noen sekunder før den sank. Kanskje jeg trenger å vokse opp og lære origami for ekte seilbåter!",
        "Hvorfor har jeg ti fingre og ikke flere? Jeg kunne hatt tolv og vært en super regner. Men kanskje vottene hadde passet dårlig da.",
        "Mamma ba meg vaske hendene, så jeg lekte at jeg var en delfin som svømte i vasken. Delfiner har rene hender, eller, kanskje ikke hender, men rene finner i hvert fall!",
        "Jeg hørte på en lydopptak av en hval, og det hørtes ut som en trist sang. Kanskje den vil ha en venn? Jeg tror jeg synger en lykkelig sang tilbake!",
        "Klokka mi går rundt og rundt, men jeg skjønner ikke helt hva tiden betyr. Jeg vet at frokost kommer først og leggetid sist. Alt midt i mellom er bare leketid!",
        "Jeg rullet meg inn i et teppe og ropte at jeg var en burrito. Pappa lo så mye at han nesten fikk vondt i magen. Burritoer burde visst ikke brøle, sier han."
    ],
    long: [
        // 50 LANGE TEKSTER (550–900 tegn, flere setninger, barnlig fortellerglede)
        "En gang drømte jeg at jeg kunne snakke med alle dyrene i hele verden. Jeg våknet med en gang og løp ut i hagen for å prøve, men den eneste som svarte, var en litt sur meitemark. Den vrikket seg som om den sa “god morgen”, men jeg var ikke helt sikker. Etterpå fant jeg en bille som kravlet på tåa mi, og jeg spurte den om den hadde et navn, men den bare fortsatte å gå som om jeg ikke var der. Kanskje jeg hadde mistet drømmespråket da jeg åpnet øynene. Mamma sa at jeg kunne prøve igjen i neste drøm, og det gleder jeg meg til. Kanskje jeg blir venner med en elefant eller en papegøye som forteller vitser!",
        "I går trodde jeg at jeg hadde funnet en skatt i hagen, for jeg gravde og gravde og fant noe som glinset i jorda. Jeg ropte på pappa for å vise ham min store oppdagelse. Men da han kom, viste det seg at det bare var en gammel foliebit som sikkert var fra en sjokolade. Jeg ble litt skuffet først, men så tenkte jeg at det egentlig var ganske gøy å late som det var ekte gull. Så jeg tok den med inn og la den i en liten boks, og nå er det min hemmelige gullskatt. Kanskje jeg bare trenger å bruke fantasien for at ting skal føles spesielt!",
        "Jeg klarte å tegne en kjempelang orm over hele arket, men så ble jeg lei av å tegne ryggmønsteret. Da bestemte jeg at den skulle ha blomster på ryggen, så jeg tegnet masse fargerike prikker. Mamma sa det var en flott fantasislange, og jeg syntes det var kult at den kunne elske blomster. Etterpå tegnet jeg en liten mus ved siden av ormen, men den var ikke redd, for jeg ga den en veldig modig farge, grønn! Da ble de nok bestevenner. Kanskje jeg skal lage en hel bok om dyr som er venner selv om de egentlig burde være redd hverandre. Det hadde vært en magisk historie!",
        "Når det regner ute, liker jeg å samle dråper på jakkeermet mitt. Jeg later som at hver dråpe er en liten krystallball med et eget univers inni. Noen ganger prøver jeg å se inn i dem for å finne miniatyrplaneter, men alt jeg ser er litt av himmelen og meg selv som speiler seg. Hvis jeg vifter litt på armen, renner de av og lager et lite rennende elveleie på jakken. Pappa sier jeg burde lukke glidelåsen så jeg ikke blir kald, men jeg har det for travelt med å leke elver. Dessuten føles det som om jeg er en mektig elvekontrollør, og det er ganske stilig!",
        "Jeg elsker at solstrålene noen ganger lager lysflekker i stua som danser rundt på gulvet. Da løper jeg etter dem og prøver å fange dem med hendene mine, men de smetter unna hver gang jeg kommer for nær. En gang prøvde jeg med en boks for å fange en skikkelig stor flekk, men så forsvant den da en sky kom forbi. Jeg følte meg litt lurt, men egentlig er det ganske spennende å jakte på noe som bare finnes i noen sekunder. Mamma sier solen liker å erte meg litt. Jeg håper den fortsetter, for det er morsomt å ha en soldans-konkurranse!",
        "I dag hadde vi en konkuranse hjemme om hvem som kunne lage det rareste ansiktet. Pappa vrengte hele fjeset så leppa gikk oppover nesen, og mamma lagde et enormt fiskeansikt. Jeg prøvde å se ut som en tiger, men jeg tror jeg bare ble en forvirret katt, for jeg kunne ikke brøle så høyt. Vi lo så mye at jeg nesten rullet bortover gulvet. Til slutt kom katten vår inn og så på oss som om vi var gale alle sammen, og da lo vi enda mer. Jeg tror katten vant uten å gjøre noe som helst, for den hadde bare et “jeg er lei av dere”-blikk. Neste gang skal jeg øve på enda rarere uttrykk!",
        "Jeg spiste en hel skål med jordbær i dag og fikk rød juice rundt munnen, så jeg så ut som en klovn. Pappa sa jeg burde vaske meg, men jeg ville egentlig gå rundt sånn hele kvelden. Da kunne jeg latet som jeg var en jordbær-superhelt som reddet bananer fra å bli brune. Men mamma tok en klut og vips var min magiske munnmaling borte. Jeg ble litt trist, men så smilte jeg da jeg fant ut at jeg kanskje kunne male meg selv med saft en annen gang. Det er litt klissete, men veldig morsomt. Jeg skal bare passe på å ikke kline det på sofaen!",
        "En gang fikk jeg låne en kjempestor paraply som var nesten like stor som meg. Jeg følte jeg bar på et lite hus, og jeg danset rundt i regnet mens dråpene trommet på taket av paraplyen. Det hørtes ut som en sang bare jeg kunne høre. Mamma sa jeg måtte passe meg så jeg ikke skled, men jeg danset videre som en pingvin på glattis. Til slutt ble jeg litt våt på beina, men det gjorde ingenting. Jeg følte meg som regndronningen, og ingen kunne stoppe meg fra å hoppe i sølepytter. Kanskje neste gang jeg tar med paraplyen, slipper jeg å bli våt på tærne!",
        "Jeg har en hemmelig skuff på rommet mitt hvor jeg legger ting som jeg syns er magiske. Der ligger en fjær jeg fant i parken, en liten stein som glitrer i sola, og et bånd jeg fikk av farmor. Jeg tror de gir meg superkrefter hvis jeg holder dem alle sammen på én gang. En gang tok jeg på meg fjæra i håret, båndet rundt håndleddet og steinen i lomma. Jeg løp rundt huset for å se om jeg ble superrask. Jeg ble andpusten ganske fort, men jeg hadde det veldig moro. Hvem vet, kanskje jeg faktisk var litt raskere enn vanlig!",
        "Da jeg var på tur i skogen, så jeg en frosk som hoppet i en dam med et kjempeplask. Jeg ropte ‘hei frosken, vent på meg!’ og prøvde å hoppe like høyt, men jeg fikk bare våte sokker. Likevel følte jeg meg litt som en skogsoppdager. Jeg fant også en pinne som lignet en tryllestav, og jeg ga trærne navn som ‘Herr Gran’ og ‘Fru Bjerk’. Hvis jeg lukket øynene, kunne jeg nesten høre at de hilste tilbake. En dag skal jeg ta med et forstørrelsesglass og lete etter små alver mellom røttene. Kanskje de venter på en femåring som vil leke!",
        "Jeg fikk en ny tannbørste med en dinosaur på, og plutselig ble tannpussen mye morsommere. Tenk at dinosaurer også må børste tenner, men de er jo kjempegamle nå, så kanskje de ikke har så mange tenner igjen? Mamma sier jeg må pusse i to minutter, og jeg teller sakte i hodet mitt. Men noen ganger glemmer jeg å telle og lager bare rare dino-lyder mens jeg pusser. Da føler jeg meg som en liten T-Rex som vil ha skinnende tenner for å skremme folk med. Heldigvis skremmer jeg ikke mamma og pappa så mye, de bare ler og sier jeg må skylle munnen ordentlig etterpå.",
        "Noen ganger våkner jeg og vet ikke helt om jeg drømmer eller er våken. I dag trodde jeg jeg var en sommerfugl og prøvde å flakse med armene for å komme meg ut av senga. Jeg fløy ingen steder, men jeg bouncet ganske høyt. Da skjønte jeg at jeg bare var en vanlig femåring med litt for mye energi. Mamma ropte at jeg måtte være forsiktig, men jeg bare lo. Kanskje jeg har sommerfuglvinger inni meg, jeg må bare vente på at de vokser fram. Inntil da får jeg øve på å fly i drømmene mine!",
        "Jeg bestemte meg for å lage en piratklubb under kjøkkenbordet. Jeg dro frem et teppe og la puter rundt så det skulle se ut som et skip. Jeg ropte “skatten er rett fram!” og pekte på mammas sko, men hun skjønte ikke at vi var på sjørøvertokt. Så snek jeg meg rundt og fant kjeks i skapet – det ble vår piratmat. Pappa spurte hvorfor alle kjeksene var borte, og jeg sa at sjørøvere spiser dem for å få energi til neste eventyr. Han bare smilte og sa jeg måtte huske å børste tennene godt etterpå. Pirater må visst også tenke på tannpuss!",
        "Tenk at en gang trodde jeg at alle dyr snakket norsk, men på en mye lavere frekvens som vi ikke kunne høre. Jeg prøvde å skru ørene mine til en hemmelig kanal, men det funket ikke helt. Kanskje man trenger en spesiell knapp inni hodet for å forstå dem. Jeg har i hvert fall ikke funnet den enda, men jeg gir ikke opp. Jeg ropte til en due at jeg var vennlig, og den kikket på meg før den fløy sin vei. Det er kanskje et tegn på at jeg nesten forstår dens språk!",
        "Jeg elsker lukten av nybakt kake, det er som om en liten fest kommer inn i nesen min. Mamma bakte sjokoladekake i dag, og jeg fikk sleike bollen. Jeg ble helt dekket av sjokolade rundt munnen, og følte meg som en sjokoladebamse. Etterpå måtte jeg ta en dusj, men det var verdt det. Tenk om man kunne lukte sånn hele tida, da hadde sikkert alle fulgt etter meg og spist meg opp. Kanskje ikke så lurt, men morsomt å tenke på!",
        "Har du prøvd å telle stjernene på himmelen? Jeg begynte i går kveld, men kom bare til 57 før jeg mistet tellinga. Og så jeg begynte på nytt, men da jeg kom til 30, ble jeg trøtt og gikk inn. Jeg lurer på om noen har klart å telle alle sammen. Kanskje det dukker opp nye stjerner hele tiden mens man teller. Det må være den største gjemsel-leken i universet! Neste gang skal jeg ønske meg en kikkert og en ekstra stor kopp kakao, så jeg ikke sovner midt i tellingen.",
        "Jeg pleier å samle løv om høsten og late som jeg er en kjempeelefant som tramper i en jungel. Løvet knitrer så herlig under beina mine. Av og til kaster jeg løvet opp i lufta og lar det regne ned over meg. Pappa sier jeg må passe meg for hundebæsj, og det prøver jeg, men noen ganger glemmer jeg å se. Da blir det kanskje en litt ekkel overraskelse, men det er fortsatt ganske gøy å ha et eget løvshow. Kanskje jeg kunne invitert vennene mine, så vi kunne hatt en løvfest sammen!",
        "Noen ganger når jeg kjeder meg, finner jeg på nye ord. I dag fant jeg på ordet ‘klukkimisj’, som betyr en slags blanding av latter og kyllinglyd. Jeg brukte det hele dagen, og mamma forsto ingenting. Hun bare spurte hva jeg mente, og jeg sa at jeg selv ikke helt visste. Men det er det fine med nye ord – de kan bety hva som helst! Kanskje jeg skal skrive en bok med alle de tullete ordene mine, så andre også kan ha det gøy med dem. Verden trenger litt klukkimisj innimellom!",
        "Jeg prøvde å lære lillesøsteren min å hoppe paradis, men hun skjønte ikke helt hvilken rute hun skulle hoppe i først. Så hun bare hoppet overalt og lo høyt. Til slutt begynte vi begge å hoppe vilt, og streken i asfalten ble bare pynt. Mamma sto i vinduet og smilte. Hun sa det så ut som vi hadde vår egen dans. Kanskje vi faktisk har det, en søsken-paradis-dans! Det var i alle fall supermorsomt, og nå er jeg litt svett!",
        "Vet du at jeg en gang var redd for en tøffel som lå på gulvet? Jeg trodde den var et lite monster med store ører. Jeg sparket borti den og ropte “gå vekk, tøffelmonster!” Men det var jo bare en tøffel. Likevel løp jeg til pappa og fortalte om det skumle monsteret. Han tok tøffelen på hånda og latet som den var en dukke som sa ‘unnskyld, jeg ville bare kose litt.’ Da lo jeg så jeg fikk vondt i magen. Tøffelmonsteret ble min venn!",
        "Jeg så et program om verdensrommet, og de sa at astronautene flyter rundt der oppe. Jeg ble skikkelig gira på å reise ut og fly, men mamma sier jeg er litt for liten ennå. Jeg sa jeg kan trene på å holde pusten lenge, men hun bare smilte. Kanskje jeg kan starte med å flyte i badekaret som en liten astronaut i vann. Jeg må bare passe på å ikke få sjampo i øynene, det er ikke så gøy. En dag skal jeg i hvert fall til månen, det er jeg sikker på!",
        "Er det ikke rart at biler har fire hjul mens sykler bare har to? Tenk om jeg hadde fire bein, da kunne jeg løpt kjempestabilt. Mamma sa at det heter en hund, men jeg er jo ikke en hund. Jeg er en femåring, men kanskje jeg kan late som jeg er en hund på karneval. Jeg kan bjeffe og løpe rundt på alle fire. Skikkelig morsomt inntil noen sier jeg må reise meg og gå som et menneske igjen. Men jeg liker å late som jeg er alle slags dyr!",
        "Jeg tegnet en hel flokk med pingviner i snø, men så gikk fargestiften min tom. Da måtte jeg farge litt med en annen blåfarge, så noen pingviner ble lysere. Jeg kaller dem pingvinfamilien, og de har en rar onkelpingvin som er knallgrønn fordi tusjen min var feil. Men det gjør ingenting, for i min tegneverden kan pingviner være alle slags farger. Kanskje jeg skal lage en gul også neste gang, som liker bananer.",
        "Da vi gikk forbi en bratt bakke, fikk jeg lyst til å rulle nedover i gresset. Mamma lo og sa jeg kunne bli grønn som en ertebøtte, men jeg gjorde det likevel. Jeg ble litt svimmel da jeg kom ned, og hodet mitt føltes som en snurrebass. Men det var verdt det, for verden så så morsom ut når jeg kikket opp på himmelen igjen. Jeg hadde litt gress i håret, men det var en fin suvenir!",
        "Har du lagt merke til at vannmelon egentlig kunne hete ‘rødsaftmelon’? Jeg mener, skallet er jo grønt, men inni er den rød. Jeg smakte en bit i dag og kjente meg som en vannsmelle, for jeg klarte ikke spise forsiktig. Saften rant nedover haka mi, og jeg lo fordi det kilt i halsen. Kanskje det er meningen at man skal bli litt klissete av vannmelon. Det føles ganske bra å være klissete noen ganger!",
        "Jeg laget en kjempefin tegning av mamma, men hun lo og sa hun så ut som et romvesen. Jeg tegnet nemlig store øyne og grønn hud. Egentlig syntes jeg hun var kjempefin, men hvis hun vil ha mer menneskefarge, kan jeg ordne det. Jeg la til litt oransje, men da så hun ut som en sol. Mamma sa at hun var glad jeg i det minste tegnet henne med et stort smil. Det får holde!",
        "I barnehagen lekte vi butikk, og jeg solgte en usynlig pizza med jordbærsmak til en venn. Han betalte meg med knapper, men jeg sa at jeg bare tar imot løvblader. Da prøvde han å bytte knappene i løv ute i hagen. Jeg syntes det var en god deal. Så spiste vi pizzaen (som ikke fantes) og klagde over at den var litt for søt. Jeg bare “ja, jordbærpizza er ikke for alle!”",
        "Når jeg sitter bak i bilen, synger jeg ofte masse sanger jeg finner på selv. Mamma og pappa sier det er mye lyd, men jeg tenker at det er fordi hjernen min har mye musikk inni seg. Av og til tar jeg en pause for å puste, og da hører jeg pappas lettede sukk. Men så begynner jeg igjen, for jeg må jo dele all sangen jeg har i meg! Kanskje jeg bør bli sanger, men jeg vil ikke ha noen som sier jeg må være stille.",
        "Jeg liker å vifte med en pinne som om det er en tryllestav. En gang klarte jeg å dytte et blad ned fra et tre med pinnen, så jeg ropte “magiii!” Pappa sa det bare var vinden, men jeg er sikker på at det var min tryllestav. Neste gang skal jeg prøve å forvandle en stein til en sjokolade. Hvis det funker, kommer jeg til å bli verdens beste sjokoladetrollmann. Hvis ikke, har jeg i hvert fall lekt meg i hagen!",
        "I dag tittet sola fram, og jeg bestemte meg for å lage en solhilsen. Jeg sto midt på plenen og viftet med armene mot himmelen mens jeg ropte “HAAALLOOO SOL!” Fikk ikke noe svar, men den skinte sterkere. Kanskje det var solens måte å si “hei” på. Jeg sprang rundt i ring til jeg ble svimmel, så la jeg meg ned og så at skyene beveget seg sakte. Det var nesten som en tegnefilm på himmelen. Jeg ville aldri gå inn, men magen rumlet, og da vant lunsjen over solhilsenen.",
        "En dag ved middagsbordet fortalte jeg en vits jeg fant på selv: “Hva kaller du en potet med hatt?” Så lo jeg før jeg rakk å svare, for jeg syntes det var så komisk. Mamma og pappa lo litt av meg, ikke av vitsen. Men jeg fant på svaret etterpå: “Hattepotet!” Det ga ikke mening, men det var gøy for meg. Jeg tror jeg har fremtiden i humorsbransjen, selv om ingen skjønte vitsen helt.",
        "Jeg besøkte bestemor, og hun hadde bakt boller med kanel i. De var så myke at jeg ville bruke dem som hodepute, men bestemor sa at jeg heller skulle spise dem. Jeg klarte ikke bestemme meg for om jeg ville sove på dem eller spise dem, men magen vant. Etterpå var jeg så mett at jeg nesten sovnet stående. Da sa bestemor at neste gang kunne vi late som bollene var puter og ta en middagslur. Hun er litt morsom sånn!",
        "En gang mistet jeg en ball i en elv, og jeg løp langs elvebredden for å se hvor den fløt. Den bare forsvant rundt en sving, og jeg ropte “kom tilbake!” Men den kom ikke. Jeg lurte på om ballen min skulle på eventyr til havet, treffe fisk og kanskje bli en undervannsboble. Pappa sa den nok bare satte seg fast i noen greiner lengre nede. Jeg liker likevel å tro at ballen min så verdens ende!",
        "I dag danset jeg i stua til en sang jeg bare fant på selv. Jeg trampa og klappa og snurra rundt, og mamma holdt på å miste kaffekoppen i gulvet fordi hun ikke visste jeg var så ivrig. Jeg sa det var en regndans, selv om det ikke regnet. Kanskje det begynner å regne senere, og da kan jeg si at jeg skapte det. Litt som en vær-gud, bare i stua!",
        "Hvorfor kalles det et garnnøste når det ikke er formet som en nøtt? Det er et mysterium. Jeg tror garnet er en stor, myk orm som sover i en ball. Hvis du drar i tråden, våkner den og strekker seg i lengder og svinger. Neste gang skal jeg prøve å kose litt med garnnøstet for å se om det blir en snill orm!",
        "Jeg prøvde å lese en bok opp ned for å se om historien ble rar, men alt jeg fikk var vondt i nakken. Bokstavene danset rundt, og jeg likte det litt. Pappa bare lo og ba meg snu boka riktig vei hvis jeg virkelig ville skjønne noe. Men noen ganger er det gøy å ikke skjønne alt. Da kan jeg finne opp min egen historie i hodet!",
        "I dag laget jeg en hemmelig klubb med bamsene mine. Vi heter Bamsebanden, og vi har et eget hemmelig håndtrykk. Jeg må føre labbene deres sammen, men det er litt vanskelig siden de ikke beveger seg. Jeg fortalte dem at de må vakte rommet mitt mot spøkelser og godterityver. Hvis de ser noe mistenkelig, skal de brumme. Men jeg har ikke hørt noe ennå, så kanskje alt er trygt.",
        "Da jeg hørte en liten lyd under senga mi, trodde jeg det var en mus med fe-hatt. Jeg stakk hodet ned og ropte “Hallo, mus!” Ingen svarte, men jeg tror den var sjenert. Kanskje jeg legger ut en ostebit neste gang, så kommer den fram. Mamma sier vi ikke skal lokke mus, men jeg vil så gjerne hilse på en mus med fe-hatt, selv om den kanskje ikke finnes.",
        "Jeg skravlet i vei i bilen, og pappa spurte hvorfor jeg alltid har så mye å si. Jeg sa at hodet mitt er som en popcornmaskin, og tankene popper ut hele tiden. Han lo og sa at det var en god forklaring. Jeg fikk lyst på popcorn da jeg sa det, men vi hadde ikke noe. Kanskje jeg må skrive ned tankene mine og selge dem som popcorn-ideer!",
        "En dag spurte jeg mamma om jeg kunne male et stort maleri av himmelen på romveggen. Hun sa at det kanskje var best å tegne på papir, men jeg syns veggen hadde vært bedre. Jeg kunne våkne og se på min egen sol og skyer. Mamma lo og sa kanskje en dag når jeg blir eldre. Men jeg vil jo gjøre det nå, for da er jeg fem år og full av sprell!",
        "Visste du at jeg prøvde å vri tunga rundt slik at jeg kunne si ord baklengs? Det var kjempevanskelig, og jeg endte opp med å si noe som hørtes ut som en and. Jeg tror jeg bare lagde en ny dyrelyd. Mamma skjønte ingenting, men lo da jeg prøvde å forklare. Kanskje jeg bare skal lage et nytt andespråk.",
        "Jeg la merke til at når jeg hopper og lander hardt, rister gulvet litt under føttene mine. Det føles som jeg er en gigant som tramper gjennom et lite landskap. Hvis jeg tramper masse, kanskje jeg kan lage et lite jordskjelv, men mamma sier jeg må være forsiktig. Jeg vil ikke ødelegge huset, bare riste litt i det!",
        "Hvis jeg samler alle fargestiftene jeg har i en boks, kan jeg lage en regnbuebombe på papiret. Det eksploderer av farger! En gang tegnet jeg et landskap som var så fargerikt at det så ut som en drøm. Mamma sa det var litt rotete, men jeg syns det var fint. Fargerot er også kunst!",
        "Jeg så en dokumentar med pappa om haier i går, og nå drømmer jeg om haier som danser ballett. Tenk om en hai kunne ha en tutu og stå på tåspissene i vannet. Den hadde vel bare svømt i sirkler. Uansett er det en morsom tanke. Kanskje jeg kan tegne en hai med rosa skjørt og store tenner, det hadde vært kjempemorsomt!",
        "I dag prøvde jeg å gjøre yoga med mamma. Jeg trodde det var lett, men så ristet beina mine som gele da jeg sto i en rar posisjon. Mamma sa jeg skulle puste rolig, men jeg ble bare fnisete av å være så krøllete. Kanskje jeg kan kalle min egen stil for “fnyse-yoga”. Jeg syns det er gøy om jeg ikke er perfekt, for da kan jeg le av meg selv!",
        "Jeg hjalp pappa med å lage pannekaker, og jeg spurte om vi kunne legge jordbær, banan, blåbær og sjokolade på samtidig. Han sa det kunne bli litt mye, men jeg insisterte. Til slutt ble pannekaka så tung at den brakk da jeg løftet den. Jeg lo så jeg nesten fikk pannekake i nesa. Det smakte fortsatt veldig godt, så alt var vellykket, egentlig!",
        "Da jeg og bestefar gikk tur, viste han meg et ekorn i et tre. Det hadde en liten nøtt i munnen og så litt overrasket ut da det så meg. Jeg lurte på om jeg skulle klatre opp for å hilse, men bestefar sa jeg kanskje skremte ekornet. Så jeg bare vinket og hvisket “hei”. Jeg tror ekornet blunket tilbake, men jeg er ikke helt sikker. Bestefar sa ekornet var nok minst like nysgjerrig på meg!",
        "Jeg fikk en luftballong i en bursdag, og den hadde helium i seg. Da pusta jeg inn litt av den og fikk pipestemme! Mamma sa “ikke gjør det for mye,” men jeg måtte bare prøve en gang til. Jeg lo så mye av min egen stemme at jeg nesten falt av stolen. Tenk om jeg kunne snakke med pipestemme hele tiden, da hadde sikkert noen trodd jeg var en liten fugl!",
        "Når jeg legger meg om kvelden, tenker jeg på alt jeg kunne drømt om. Jeg skriver ønskene på en usynlig tavle i hodet mitt. Kanskje det gjør at jeg drømmer ekstra morsomt, som å fly med enhjørninger eller spise is på en sky. Noen ganger drømmer jeg bare noe tullete jeg ikke husker neste morgen. Men jeg liker tanken på at jeg kan velge drømmene mine, selv om jeg egentlig ikke kan det. Det er litt magi i å prøve!",
        "Har du sett en blekksprut på TV før? Den spruter blekk og har masse armer. Jeg tenker at den kunne gitt meg klem med åtte armer, det er ganske imponerende. Samtidig kan den bare stikke av i en sky av blekk, så du ikke ser den mer. Jeg vil kanskje ikke ha blekksprutblekk i ansiktet. Men en liten blekksprutklem hadde vært kult, eller hva?",
        "Jeg hørte at man kan se nordlys om natta hvis det er riktig vær. Da tenkte jeg at nordlyset er en dansende regnbue som bare kommer på besøk av og til. Kanskje jeg roper “kom ned og si hei!” Men det vil nok bare fortsette å danse i himmelen. En gang vil jeg reise et sted hvor det er masse nordlys, så jeg kan vinke og bli med i dansen. Foreløpig får jeg bare tegne mitt eget nordlys på et svart ark!",
        "I dag spiste jeg grøt til frokost, og den så ut som en klissete vulkan da jeg helte på syltetøy. Jeg late som den eksploderte, og skjeen min reddet folket som bodde rundt vulkanen. Pappa spurte hva i all verden jeg drev med, men jeg sa bare at grøtvulkanen måtte stoppes! Etterpå var jeg klissete i fjeset og måtte vaske meg, men det var absolutt verdt det. Man må ha litt action selv når man spiser frokost!",
        "Hvis jeg sto opp tidlig nok til å se sola stige, ville jeg ropt “God morgen, sol!” Men det er litt for tidlig, jeg orker ikke stå opp da. Kanskje jeg må legge meg på en solstol utenfor og vente. Mamma sier jeg ikke får være alene ute så tidlig, så jeg må nok vente noen år. Men jeg har et bilde i hodet av hvordan sola smiler idet den kryper opp på himmelen. Det er ganske fint å tenke på før jeg sovner!",
        "Jeg synes det er gøy å høre ekko i en tunnel, for det er nesten som å snakke med en hemmelig venn. Jeg roper “hallooo,” og så svarer en litt rar versjon av meg. Jeg lurer på hva som skjer hvis jeg hvisker en hemmelighet, får jeg en hemmelighet tilbake? Mamma sier ekko bare er lyden som spretter, men jeg vil tro at tunnelen er magisk. Det er morsommere sånn!",
        "Da jeg var syk, drakk jeg varm saft og spiste saltstenger i senga. Det føltes som en liten fest der jeg var invitert alene. Mamma passet på meg som en sykepleier, og jeg latet som jeg var en konge med dyne-kappe. Hun tok temperaturen min og sa “du er varm,” og jeg svarte “ja, for jeg er en flammekonge!” Det fikk oss begge til å le litt, og jeg ble bedre snart.",
        "Jeg elsker at forskjellige dager kan føles helt nye, selv om jeg er i det samme huset. Kanskje sola står annerledes, eller jeg våkner i godt humør. Noen dager er jeg litt sur og vet ikke hvorfor, men så skjer det noe gøy som får meg til å le. Mamma sier det er normalt å være litt humørsyk iblant. Jeg tror hjernen min bare trenger litt frokost for å bli glad igjen. Frokost løser alt!",
        "Hvis jeg ser en stjerneblink på kvelden, later jeg som det er en liten alien som vinker fra langt borte. Kanskje den sier “Hei, jordboer!” Jeg roper “Hei, stjerneboer!” men jeg vet jo at den ikke hører meg. Det er likevel fint å late som jeg har en venn i universet. Kanskje en dag kommer den for å hilse på meg, men da må den finne romdrakt i min størrelse først!",
        "Jeg gikk på tur med barnehagen, og vi fikk se en gigantisk maurtue. Den hadde tusenvis av maur, og jeg tenkte at det var deres egen by med gater og hus. Jeg spurte om jeg kunne flytte inn der, men tante i barnehagen sa jeg nok ble for stor. Dessuten biter maur om de blir stressa. Kanskje jeg bare skal bygge en mini-maurtue hjemme av pinner, så kan jeg late som jeg er kongen av Maurlandia. Det hadde vært kult!",
        "Har du prøvd å klø deg selv på ryggen med en pinne? Jeg gjorde det i dag, og det var litt deilig men også litt skummelt. Tenk om pinnen plutselig fikk splinter i ryggen min? Mamma sa jeg burde bruke en kløpinne som er laget for sånt, men jeg hadde ikke det. Uansett var det et morsomt eksperiment, og nå vet jeg at pinner fungerer, men er litt risky!",
        "Jeg inviterte nabogutten til å spille stein-saks-papir, men han sa han heller ville sykle. Da ropte jeg “vente litt, jeg må finne saks og papir!” Men så husket jeg at det bare er en lek, så jeg lo av meg selv. Vi endte opp med å tegne racerbaner med kritt på asfalten og syklet rundt. Jeg vant, men jeg tror egentlig vi begge vant. Det var kjempegøy!",
        "Noen ganger når jeg ser en liten bekk, får jeg lyst til å hoppe over den. Men jeg blir litt redd for å falle i vannet. Så jeg står og tripper en stund før jeg hopper. Hvis jeg lander på en stein midt i bekken, må jeg bare smile og late som jeg planla det sånn. Jeg tror man lærer av å hoppe, selv om man noen ganger havner litt i vannet. Det er en del av moroa!",
        "Jeg syns hver dag burde ha et navn som beskriver den. Som ‘Sukkertirsdag’ når vi har pannekaker, eller ‘Regntorsdag’ når det regner masse. Mamma sier at det blir for mange forskjellige navn å huske på. Men jeg tenker at hvis jeg var sjef i kalenderfabrikken, skulle jeg gitt hver dag en gøyal tittel. Så kunne folk glede seg mer til den neste morsomme dagen!",
        "Jeg leste en bok om en kjempe som var snill, og da lurte jeg på om kjemper egentlig er bare store barn. Kanskje de vil hoppe tau og klatre i trær, men trærne knekker. Jeg tror jeg ville vært venn med en kjempe hvis den fantes, men jeg skulle nok passet meg for store klemmer. Mamma klemmer meg noen ganger så hardt at jeg får latterkrampe, men en kjempe-klem hadde nok klemt meg flat, haha!"
    ]
};
