import type { TextCollection } from '../types';

export const legalTexts: TextCollection = {
		short: [
		"Rettslig vurdering pågår.",
		"Forholdet reguleres av gjeldende lovverk.",
		"Partene har inngått en avtale.",
		"Ansvarsforhold må avklares.",
		"Vilkår og betingelser gjelder.",
		"Dokumentet er under revisjon.",
		"Ingen entydig konklusjon kan trekkes.",
		"Rettspraksis varierer etter jurisdiksjon.",
		"Samtykke kreves i visse tilfeller.",
		"Forbehold må vurderes nøye.",
		"Ansvaret avhenger av sakens natur.",
		"Lovbestemmelser kan tolkes ulikt.",
		"Gyldighetsperioden er fastsatt i avtalen.",
		"Eventuelle tvister håndteres separat.",
		"Dokumentasjon må foreligge ved forespørsel.",
		"Tolkningsspørsmål kan oppstå.",
		"Begrensninger er definert i avtalen.",
		"Tidsfrister må overholdes i henhold til forskrift.",
		"Klausuler kan påvirke utfallet.",
		"Hensynet til partenes interesser skal ivaretas.",
		],
		medium: [
		"Avtalens innhold tolkes i lys av gjeldende rettspraksis.",
		"Enhver tvist mellom partene skal løses etter avtalens bestemmelser.",
		"Juridiske vurderinger baseres på en helhetlig analyse av saken.",
		"Rettighetene kan variere avhengig av partenes forpliktelser.",
		"Dokumentets innhold kan justeres i henhold til gjeldende lovgivning.",
		"Rettslige prosesser krever en grundig gjennomgang av tilgjengelig dokumentasjon.",
		"Ansvarsfordelingen mellom partene er definert i avtalens tredje ledd.",
		"Vilkår kan endres ved gjensidig skriftlig samtykke mellom partene.",
		"Tolkningsspørsmål kan oppstå ved uklarheter i de avtalte forpliktelsene.",
		"Dersom uenighet oppstår, skal partene først forsøke å finne en minnelig løsning.",
		"Gyldigheten av en avtale avhenger av dens overholdelse av formkrav.",
		"Lovgivningen på området er gjenstand for fortløpende endringer.",
		"Eventuelle krav må fremmes innenfor de lovbestemte fristene.",
		"Kontraktsbrudd kan medføre erstatningsansvar etter gjeldende rett.",
		"Innholdet i avtalen er juridisk bindende for begge parter.",
		],
		long: [
		"Enhver avtale mellom partene skal tolkes i samsvar med avtalelovens bestemmelser, og eventuell uenighet skal søkes løst gjennom forhandlinger før saken bringes inn for domstolene. Dette innebærer at partene i utgangspunktet forplikter seg til å finne en gjensidig tilfredsstillende løsning gjennom dialog og mekling. Dersom forhandlingene ikke fører frem, kan tvisten bringes inn for de ordinære domstolene eller eventuelt behandles gjennom voldgift dersom dette er avtalt. Avtalevilkårene skal tolkes i lys av partenes opprinnelige intensjoner, og enhver uklarhet skal i utgangspunktet gå ut over den parten som har utformet vilkårene. Forpliktelser som ikke er eksplisitt angitt i avtalen, kan tolkes i samsvar med sedvane, praksis og relevant rettspraksis.",
		"I tilfeller hvor det foreligger motstrid mellom ulike bestemmelser i kontrakten, skal den tolkningen som best samsvarer med avtalens formål og intensjon legges til grunn. Det skal særlig legges vekt på om bestemmelser er spesifikke eller generelle, og hvorvidt det foreligger føringer i tidligere inngåtte avtaler mellom partene. Dersom det ikke er mulig å fastslå en entydig tolkning, skal prinsippet om lojalitetsplikt mellom partene benyttes som en tolkningsfaktor. Videre kan det tas hensyn til hvordan lignende avtaler tidligere har blitt tolket i lignende tilfeller, samt relevante lover og forskrifter som regulerer avtaleforholdet. Eventuelle endringer i lovgivningen kan også påvirke kontraktens gyldighet og anvendelse.",
		"Partene forplikter seg til å opptre i god tro og følge de forpliktelser som er pålagt i henhold til avtalens innhold og det til enhver tid gjeldende lovverk. God tro innebærer at partene skal opptre redelig, hensynsfullt og lojalt overfor hverandre, både ved inngåelsen av avtalen og under gjennomføringen av de avtalte forpliktelsene. Eventuelle uklarheter eller misforståelser skal avklares i samsvar med prinsippet om kontraktstolkning til fordel for den svakere parten, dersom dette er relevant. Dersom en av partene har handlet i strid med denne forpliktelsen, kan det medføre krav om erstatning eller andre rettslige konsekvenser.",
		"Dersom en avtalebestemmelse anses som ugyldig eller ikke kan håndheves, skal dette ikke påvirke de øvrige bestemmelsenes gyldighet eller håndhevbarhet. Det betyr at selv om en spesifikk klausul i kontrakten anses å være i strid med lov eller anses ugyldig av domstolene, skal resten av avtalen fortsatt være gyldig og bindende for partene. Dersom en ugyldig bestemmelse har vesentlig betydning for avtalens gjennomføring, kan det imidlertid være nødvendig å reforhandle vilkårene eller finne en alternativ løsning som sikrer partenes rettigheter og forpliktelser.",
		"Rettspraksis på området viser at domstolene legger vesentlig vekt på partenes intensjoner ved inngåelsen av en avtale, og tolkning av uklare vilkår skjer i samsvar med etablerte tolkningsprinsipper. En domstol vil typisk vurdere hvordan avtalen ble inngått, hvilke ytre omstendigheter som forelå, samt hvilken forståelse partene selv har hatt av avtalens innhold. Dette innebærer at dersom en tvist oppstår, vil det være avgjørende hvordan partene faktisk har praktisert avtalen i etterkant av signeringen. Formålet med avtaletolkning er å oppnå en balansert løsning som reflekterer partenes reelle forutsetninger.",
		"Ved uenighet om kontraktens innhold eller oppfyllelse, skal partene først søke en løsning gjennom forhandlinger eller megling før rettslige skritt vurderes. Dette innebærer at formelle rettslige prosesser bør være en siste utvei dersom partene ikke klarer å finne en minnelig løsning på tvisten. I tilfeller hvor uenigheten er av en slik art at den ikke kan løses ved dialog, kan en part vurdere å bringe saken inn for en nøytral tredjepart, som en voldgiftsrett eller en domstol. Hensikten med slike prosesser er å sikre at tvisten løses på en mest mulig rettferdig og objektiv måte.",
		],
};