import type { TextCollection } from '../types'; 

export const publicsectornynorskTexts: TextCollection = {
    short: [
        "Ny innsending registrert; handsaming startar straks.",
"Ver merksam på svarfrist som gjeld for dokumenta dine.",
"Saksgangen stoppast om obligatoriske vedlegg manglar.",
"Systemet oppdaterer status automatisk kvar natt kl. 03.",
"Søknaden er komplett; vent på vedtak i digital post.",
"Ufullstendige felt kan føre til lengre behandlingstid.",
"Du kan spore framdrifta i din personlege innboks nå.",
"Endra arbeidssituasjon må meldast innan fem dagar.",
"Kvittering vert sendt når alt er korrekt motteke.",
"Vennleg rett opp feil i skjema før innsending.",
"Manglar du PIN-kode, kan ny bestillast på nett.",
"Nye retningsliner gjeld frå og med neste månad.",
"Tildelt saksnummer skal brukast i all korrespondanse.",
"Elektronisk signatur må vere på plass før vi startar.",
"Eit varsel vert sendt om vi treng ytterlegare data.",
"Du kan trekkje søknaden ved å trykke «Avbryt prosess».",
"Omlagleg handsamingstid er tre til fem arbeidsveker.",
"Hugs å lagre undervegs for å unngå tap av informasjon.",
"Bekrefta opplysningar vert delte med relevante register.",
"Betalingsfrist vert rekna frå dato for vedtaket.",
"Informasjon om klagerett ligg i mottatt vedtaksbrev.",
"Systemet støttar både bokmål og nynorsk språkform.",
"Datasikkerheit er ivareteken gjennom kryptert overføring.",
"Saksinnsyn krev pålogging med høgt tryggleiksnivå.",
"Nytt regelverk kan få innverknad på godkjent beløp.",
"Ved feilutbetaling må beløpet refunderast snarast.",
"Endringar i folkeregistrert adresse meldast automatisk.",
"Du vert varsla om møtetid via SMS to dagar før.",
"Skanna kvitteringar må vere lesbare og komplette.",
"Alle felt markerte med stjerne er obligatoriske.",
"Innsendt dokumentasjon vert sletta etter arkivfrist.",
"Du kan leggja til representant med fullmakt i portalen.",
"Krav om attester må vere stadfesta av autorisert instans.",
"Systemvedlikehald kan føre til kort nedetid søndag kveld.",
"Forlenging av frist må grunngjevast skriftleg før tidsutløp.",
"Nye vedlegg kan lastast opp så lenge saka ikkje er låst.",
"Utbetaling skjer til kontoen som er registrert hos oss.",
"Vedtaket kan ikkje påklagast etter tre vekers frist.",
"Du kan abonnere på statusoppdateringar via e-post.",
"Personopplysingar vert lagra i tråd med gjeldande lov.",
"Automatisk validering hindrar formelle feil i skjema.",
"Dersom du stadfestar, kan opplysningar ikkje endrast.",
"Oppgi korrekt organisasjonsnummer for arbeidsgivar.",
"Legitimering må gjerast før fysiske møte i skranken.",
"Vi tek kontakt dersom det oppstår behov for intervju.",
"Systemet loggar alle innloggingar for revisjonsspor.",
"Nedlastbar kvittering ligg tilgjengeleg i 90 dagar.",
"Manglar du BankID, kan du nytte alternativ kodebrev.",
"Melding om vedtak vert også sendt til Altinn-boksen din.",
"Svarfristen vert rekna frå dagen etter melding er sendt.",
"Merk at stønad kan justerast ved endring i inntekt.",
"Dokumentasjonen vert kontrollert opp mot eksterne kjelder.",
"Foreløpig svar vert ikkje rekna som endeleg vedtak.",
"Uteståande gebyr må vere betalt før vidare behandling.",
"Systemet slettar mellombels data etter 72 timar inaktivitet.",
"Kontakt brukerstøtte dersom tekniske problem vedvarer.",
"Kvifor-feltet bør gi kort, presis grunngjeving for behov.",
"Papirdokument må vere stempla og signert av rett instans.",
"Innleverte originale attestkopiar vert returnerte i posten.",
"Stadfest korrekte kontonummer for raskare utbetaling.",
"Nytt skjema vert tilgjengeleg frå komande versjon.",
"Sjekk at opplastingsformat er PDF, JPG eller PNG.",
"Tidsstempel for innsending ligg i kvitteringslogg.",
"Tilleggsløyving krev ny godkjenning frå fagansvarleg.",
"Status «Under vurdering» betyr at sakshandsamar er tildelt.",
"Vi sender påminning éin dag før dokumentfrist går ut.",
"Kopi av vedtak vert arkivert i di digitale mappe.",
"Elektronisk arkiv krev ikkje papirutskrift til deg.",
"Du kan lagre utkast lokalt før endeleg innsending.",
"Statistiske data vert brukte utan personidentifikasjon.",
"Avslått søknad kan sendast inn på nytt med ny dokumentasjon.",
"Kontakt kommunen dersom du har bustad-relaterte spørsmål.",
"Systemet støttar skjermlesar for universell utforming.",
"Før inn korrekt fakturadato for å unngå avvising.",
"Ingen personopplysingar vert delte med tredjepart utan samtykke.",
"Tilskot vert avkorta dersom vilkår ikkje er oppfylt.",
"Ikkje send same dokument fleire gonger, det forsinkar prosessen.",
"Stadfest at alle sider er med før du lastar opp skanna filer.",
"Endring av kontaktinformasjon trer i kraft umiddelbart.",
"Oppgjev bruttoinntekt, ikkje netto, i relevante felt.",
"Systemet lagrar endringar fortløpande medan du fyller ut.",
"Arkiver notar lokalt dersom du treng dei til eige bruk.",
"Dersom fødselsdato er feil, stans og rett opp før innsending.",
"Kryss av for rett type vedlegg i opplastingsmenyen.",
"Du treng ikkje sende oss postleg kopi av digital innsending.",
"Pålogga sesjon vert automatisk logga ut etter to timar.",
"Feilkode 400 tyder vanlegvis på manglande pålagde felt.",
"Kontroller at totalsum stemmer før du godkjenner søknaden.",
"Frådrag vert kalkulert etter gjeldande sats ved vedtakstidspunkt.",
"Klage må innehalde konkret grunngjeving og evt. nye opplysningar.",
"Eventuelle renter vert utbetalte samstundes med hovudbeløpet.",
"Systemet stadfestar mottak med e-post umiddelbart.",
"Godkjenning krev at all informasjon er sannferdig.",
"Skattedata vert henta automatisk, du treng ikkje leggje ved skattemelding.",
"Ver merksam på at felt for stillingsprosent ikkje kan stå tomt.",
"Har du fleire roller, vel rett funksjon før utfylling.",
"Nytt passord må vere på minst tolv teikn med særteikn.",
"Vi godtek ikkje zip-filer grunna sikkerheitsrestriksjonar.",
"Trykk «Fullfør» for å låse skjemaet før innsending.",
"Kryptert kvitterings-PDF kan opnast med fødselsdato som passord.",
"Varsling via SMS kan avbestillast under personlege innstillingar.",
"Etterregistrering av timelister må gjerast innan fem dagar.",
"Våre opningstider for telefon er kl. 09–15 alle kvardagar.",
"Dersom dokumentet er uleseleg, vert det avvist automatisk.",
"Datasett vert spegla til backup-sone kvar natt.",
"Innsendt fullmakt vert verifisert mot folkeregisteret.",
"Maksimal filstorleik er 25 MB per enkeltvedlegg.",
"Brannmur kan blokkere eldre nettlesarar frå innlogging.",
"Når signatur er stadfesta, vert tidsstempel uforanderleg.",
"Lag endringane dine før du forlet denne sida.",
"Ved manuell sjekk kan behandlingstida verte noko lengre.",
"Systemet støttar ikkje emoji-teikn i tekstfelt.",
"Kontroller at korrekt språkform er vald før du skriv ut.",
"Deling av skjerm kan vere naudsynt ved fjernstøtte.",
"Tilfeldige stikkprøvar sikrar rett bruk av ordningar.",
"Treng du tolk, kryss av i feltet for tilrettelegging.",
"Arkivnøkkel vert generert automatisk ved sluttføring."
],
    medium: [
        "For å sikre rask behandling ber vi deg gjennomgå alle vedlegga ein gong til før innsending. Manglande dokumentasjon kan føre til at saka vert sett på vent og fristen automatisk forlenga.",
"Dersom arbeidsforholdet ditt endrar seg under prosessen, må du straks registrere ny stillingsprosent. Uoppdaterte opplysningar kan medføre feil utrekning av yting og mogleg krav om tilbakebetaling.",
"Når skjemaet er fullført, vert ei kvittering generert som PDF. Denne fungerer som juridisk stadfesting på at opplysningane er mottatt og kan ikkje endrast utan ny innsending frå brukaren.",
"Vi minner om at alle personlege data vert handsama i tråd med personvernforordninga. Systemet lagrar berre nødvendig informasjon, og overskytande felt vert automatisk sletta etter 72 timar.",
"Innsynsløysinga gjev deg høve til å spore kvar enkelt sakshandling i sanntid. Loggen viser tidspunkt, status og ansvarleg rolle, slik at du til ei kvar tid kan dokumentere framdrift internt.",
"Elektronisk signatur må knytast til gyldig legitimasjon. Om BankID ikkje er tilgjengeleg, kan du nytte alternativ ID-porten-metode, men dette vil kunne utsetje vidare automatisert validering.",
"Systemet godtek berre filformat PDF, JPG og PNG. Forsøk på å laste opp andre format vil resultere i feilkode 415 og stanse innsendinga fram til filene er konverterte til støtta format.",
"Alle beløp skal oppgjevast i norske kroner utan skiljeteikn. Systemet avrundar automatisk til nærmaste heile beløp ved lagring for å unngå avrundingsavvik i etterfølgjande budsjettkontroll.",
"Om du har motteke forskotsutbetaling, vert denne avrekna mot endeleg vedtak. Eventuelt overskot vil bli etterfakturert med forfall ti dagar etter at avsluttande faktura er sendt ut elektronisk.",
"Vedlegg som inneheld sensitive helseopplysningar skal merkast med nivå H. Filene vert då krypterte i kvile og ved overføring, og er utilgjengelege for saksbehandlar utan særskild tilgangsstyring.",
"Påminning om frist vert sendt via SMS og e-post tre dagar før tidsgrensa. Har du deaktivert varslingskanalar under personlege innstillingar, pliktar du likevel å overhalde oppgitt dato.",
"Skjemaet har innebygd regelmotor som stoppar deg dersom obligatoriske felt manglar. Det er difor unødvendig å sende følgeskriv med oversikt; systemet dokumenterer alt i kvitteringa.",
"Etter at vedtak er fatta, ligg grunnlaget tilgjengeleg for klage. Du må sende eventuell klage innan tre veker og leggje ved nye opplysningar som kan påverke resultatet av avgjerda.",
"I samband med systemvedlikehald kan tenesta vere utilgjengeleg sundag mellom klokka 22 og 02. Planlagde avbrot vert varsla på framsida minst 48 timar før nedetid tek til å gjelde.",
"Dokument som vert returnerte i posten grunna feil adresse, vert oppbevarte i seks månader før destruering. Du kan melde frå via kontaktskjema dersom du ønskjer ny utsending innan fristen.",
"Stønad vert justert årleg i samsvar med konsumprisindeksen, med verknad frå 1. januar. Endringane kjem automatisk på betalingsplanen og krev inga handling frå deg som mottakar.",
"Du kan dele midlertidig innsynslenkje med revisor eller rådgivar. Lenkja er gyldig i sju dagar og krev totrinnsverifisering før tilgang vert gjeven til tilhøyrande dokument.",
"Når du slettar eit utkast permanent, kan det ikkje gjenopprettast. Vi rår deg difor til å laste ned lokal kopi dersom du ønskjer å behalde informasjonen til interne arkivformål.",
"Førehandsgodkjenning frå kommunen er naudsynleg dersom prosjektet inneber endring av eksisterande bygningsmasse. Last opp stadfesting saman med hovudskjema for å unngå ytterlegare purring.",
"Systemet hentar skattegrunnlaget ditt direkte frå Skatteetaten. Du treng difor ikkje laste opp skattemelding, men ver merksam på at feil eller manglande oppdateringar kan påverke berekningsgrunnlaget.",
"Eventuelle renter på etterbetaling vert berekna frå vedtaksdato og fram til reell utbetalingsdato. Rentesatsen følgjer Finansdepartementet sine føringar og blir oppdatert kvart halvår.",
"Når data vert delte med eksterne fagetatar, loggar systemet mottakar, formål og tidsstempel. Du kan sjå oversikt over delingar i personleg aktivitetshistorikk under «Dataspor» i menyen.",
"Om du ikkje har mottatt kvittering innan to timar etter innsending, kan det tyde på at prosessen har stoppa. Kontakt brukerstøtte, og oppgje referansekode som vart vist då skjemaet vart sendt.",
"Dersom du nyttar førebels tall for sjølvstendig næringsdrivande inntekt, pliktar du å ettersende revidert resultat når likningsoppgjeret ligg føre, elles kan tilskot verte etterjustert.",
"Alle førespurnader vert svara ut i den rekkjefølgja dei kjem inn. Du treng difor ikkje sende fleire like e-postar; dette kan i verste fall føre til at saksbehandlinga tek endå lengre tid.",
"Når du legg til ein ny kontaktperson, må fullmaktsskjema signeres digitalt av begge partar. Systemet sender varsel til ny kontakt for godkjenning før rettar vert aktive.",
"Kvalitetssikringa vår inneheld automatiske stikkprøvar. Vert di sak vald, kan vi be om ytterlegare dokumentasjon innan sju dagar. Manglande svar gir grunnlag for midlertidig stans.",
"PDF-vedlegg vert kjørt gjennom OCR for søkbarheit. Om filene inneheld handskrift, kan du bli beden om tydelegare skann eller utskriftsvenleg versjon for å sikre lesbar dokumentasjon.",
"Felt for fødselsnummer validerer kontrollsiffer ved lagring. Oppdagar du likevel feil etter innsending, må du kontakte brukerstøtte for manuell korrigering før vidare handsaming.",
"Bokføring av innbetalingar skjer fortløpande kvardagar kl. 12.30. Transaksjonar registrert etter dette tidspunktet blir synlege i systemet neste arbeidsdag.", 
"Innsendt klage vert først kontrollert for formkrav. Oppfyller den ikkje vilkåra, får du høve til å rette innan ti dagar. Uendra klage vert avvist utan ny realitetsbehandling.",
"Ved overgang frå midlertidig til permanent støtteordning vert siste vedtak automatisk oppheva og erstatta. Du får eige brev som forklarar konsekvensar av overgangen.",
"Brannmuren vår blokkerer filar større enn 25 MB. Del store dokument inn i fleire vedlegg eller bruk komprimering utan passord dersom original storleik overskrid grensa.",
"Dersom du treng utskriftskopi av elektronisk vedtak, kan du bestille attest via skjema «Bestill papir». Normal leveringstid er fem arbeidsdagar frå mottatt ordre.",
"Avsluttande rapport skal sendast inn innan 30 dagar etter prosjektperiode. Ufullstendig rapport kan føre til krav om delvis tilbakebetaling av tilskot og renter.",
"Vi godtek ikkje opplysningar som berre er skriven i fritekst dersom skjemaet har eige strukturert felt. Du må difor fylle ut alle spesifikke felt for å bestå validering.",
"Endring i kontonummer krev totrinnsverifisering og stadfesting av e-postadresse. Det nye kontonummeret vert aktivt først når begge stega er fullførte og logga.",
"Føresegner om offentleg innsyn gjeld etter offentleglova. Delar av doku­ment kan likevel bli unndratt dersom lova om tausheitsplikt krev det for å verne personlege forhold.",
"Om du har gitt samtykke til elektronisk kommunikasjon, vil all korrespondanse gå via digital postkasse. Brev på papir vert berre sendt ved særskild behov eller systemfeil.",
"Systemet lagrar automatisk versjonar av skjemaet under utfylling. Du kan gjenopprette tidlegare versjon inntil 30 dagar etter siste endring før det permanent slettast.",
"Filnamn skal ikkje innehalde spesialteikn eller lange blanksteg. Filnamn som bryt regelen vert automatisk endra av systemet før lagring for å sikre kompatibilitet.",
"Kvar gong du loggar inn, vert IP-adresse og tidsstempel lagra for revisjon. Desse dataene vert sletta etter 180 dagar dersom dei ikkje trengst i ein aktiv gransking.",
"Vidareformidling av informasjon til sakkyndig vert gjort gjennom lukka kanal. Du treng ikkje sende kopi manuelt, då systemet distribuerer relevant materiale kryptert.",
"Opplasta dokument skal vere i originalfargar. Svart-kvitt kan godtakast dersom kontrast er høg, men sikring av signatur og stempel vert svakare og kan føre til ny purring.",
"Når du stadfestar sjølverklæring, tek du det fulle ansvaret for at innhaldet er korrekt. Feilaktige opplysningar kan resultere i administrative reaksjonar eller straffesanksjonar.",
"Før du sender melding via kontaktsenteret, sjekk FAQ-seksjonen. Mykje vanlege spørsmål er besvarte der og kan gje raskare løysing enn å vente på svar frå saksbehandlar.",
"Kryptert e-post krev støtte for S/MIME eller PGP i klienten din. Dersom dette ikkje er konfigurert, vil melding bli levert som lenkje til trygg nettportal med eingongskode.",
"Ved høg pågang prioriterer vi saker kronologisk. Hastemerking vert berre innvilga ved dokumentert fare for økonomisk tap eller friststyrt lovpålagt rapportering.",
"Kostnader som overstig tilskotsramma må dekkast av søkar. Systemet avkortar automatisk alle beløp som ligg over øvre grense for godkjende utgifter i budsjettfeltet.",
"Vi nyttar tostadig godkjenning på alle rolleendringar. Fyrste steg er elektronisk; andre steg krev manuell verifikasjon frå intern administrator før rolla vert aktiv.",
"Logg over førehandsvarsel vert lagra i minimum fem år i tråd med arkivforskrifta. Etter perioden vert loggen anonymisert for statistisk bruk og deretter sletta.",
"Når du sender forespurnad på vegner av verksemda, må du legge ved signert protokoll som gir deg fullmakt. Utan gyldig fullmakt vil vi måtte avvise innsendinga.",
"Saksbehandlar kan setje fråsegn til «Utsett» dersom dokumentasjonen er uklar. Du får då e-post med presis rettleiing om kva som må korrigerast før ny vurdering.",
"Forbruk av midlar skal dokumenterast med hovedbok og bilag. Manglande grunnlagsdata fører til trekk i siste utbetaling eller krav om tilbakebetaling av tidlegare rate.",
"Systemet sender automatisk kvittering når du har lasta opp alle påkravde vedlegg. Om feltet for «Send til vurdering» ikkje er tilgjengeleg, er skjemaet framleis ufullstendig.",
"Nye regelendringar vert automatisk implementerte i berekningsmotoren. Du kan difor sjå avvik i beløp frå tidlegare simulering dersom satsane er oppdaterte mellom innloggingar.",
"Om du gløymer passordet, kan du be om tilbakestilling. Lenkje til nytt passord er giltig i éin time og kan berre nyttast frå same IP-adresse som anmodninga vart send frå.",
"Krav som vert sende inn etter at fristen har gått ut, vert avvist. Du kan likevel søkje om oppreising ved å forklare forseinkinga og leggje ved relevant dokumentasjon.",
"Postadresse kan ikkje endrast i skjemaet når sak er låst. Du må då bruke «Meld endring» etter vedtak. Endringa vert logga som eigen transaksjon med nytt tidsstempel.",
"Samordning med andre ytingar skjer maskinelt. Om du alt har motteke støtte frå annan ordning, vert beløpet automatisk redusert for å unngå dobbeltfinansiering.",
"Alle timesatsar er baserte på gjeldande hovudtariffavtale. Dersom søknaden inneheld annan timesats, vert beløpet retta av systemet før oversending til saksbehandlar.",
"Krediteringsnota vert tilgjengeleg som eigen post i fakturajournalen når eventuell feilutbetaling er korrigert. Merk at renter vert handtert i separat transaksjon.",
"Vi kan bestille stadfesting frå eksterne register ved tvil om identitet. Slike oppslag vert loggførte, men du vil ikkje alltid få varsel dersom verifikasjonen er automatisk.",
"Systemet nyttar tidsstempla kontrollsum for å avdekke endring av filer etter innsending. Manipulerte dokument vert avvist, og du vert informert om mogleg årsakskode.",
"Val av språkform gjeld berre brukargrensesnitt. Dokumenta i vedtakspakken vert produserte på bokmål, nynorsk eller engelsk avhengig av di personlege innstilling.",
"Når du har sendt inn søknad, kan du ikkje leggje til fleire vedlegg før ho er handsama. Treng vi tilleggsinformasjon, får du ein eigen lenkje for ettersending.",
"Oppdragstakarar skal registrere timebruk i eige feltsystem. Kun aggregert timetal skal leggast inn her; detaljerte lister må oppbevarast lokalt for eventuell kontroll.",
"Avgiftssatsar vert henta frå toll- og avgiftsdatabasen kl. 06 kvar morgon. Berre satsar registrert pr. behandlingstidspunkt vert brukte i den juridiske vurderinga.",
"Korreksjon av selskapstal etter fristen krev vedtak om omgjering. Du må difor sende formell førespurnad med grunngjeving, signert av dagleg leiar eller styreleiar.",
"Klageinstansen kan berre ta stilling til forhold som er påklaga. Nye krav som ligg utanfor opphavleg sak, må sendast som separat søknad med eige saksnummer.",
"Om styringsgruppa krev ekstra rapportering, vert eigne felt opna i skjemaet. Du får varsel med referanse, og frist vert sett til minimum ti arbeidsdagar fram i tid.",
"Personvernombodet vårt fører tilsyn med all handsaming av data. Har du spørsmål, kan du sende kryptert melding via kanalen «Kontakt personvern» i hovudmenyen.",
"Sidan skjemaet støttar universell utforming, kan tastaturnavigasjon brukast for alle felt. Skjemaet er testa med skjermlesarar NVDA og VoiceOver, versjonar 2024.",
"Skriv inn minusbeløp med fortegn, ikkje parentes. Systemet konverterer automatisk til korrekt regnskapsformat ved lagring i budsjettseksjonen.",
"Blir du inaktiv i skjemaet i meir enn tjue minuttar, får du eit varsel før automatisk utlogging. Varselet let deg forlenge sesjonen med éin klikk.",
"Kommunale satser kan avvike frå statlege. Hvis kommunen har lågare eigenandel, vert systemet automatisk justert etter postnummer i folkeregisteret.",
"Alle felt med blå kant er førehandsutfylte frå nasjonale register. Du har moglegheit til å rette, men systemet loggar avvik og kan be om dokumentasjon.",
"Konverter valuta manuelt dersom kostnader i skjemaet er i euro. Systemet nyttar Noregs Bank si daglege vekslingsrate for samsvar og arkivering.",
"Ettersending av passkopi skal innehalde foto- og signaturside. Systemet sjekkar automatisk at filstorleik er over 500 kB for å sikre lesbar kvalitet.",
"Dersom prosjektet har fleire delaktivitetar, må du nytte eigen budsjettlinje per aktivitet. Systemet summerer automatisk og viser totalsum i oversikt.",
"Tast inn telefonnummer utan mellomrom eller landskode. Systemet legg på +47 automatisk når data vert validerte og lagra i kontaktregisteret vårt.",
"Innkjøp over kr 100 000 må dokumenterast med tilbodsrunde. Last opp kopi av minst to tilbod. Ufullstendig konkurranseprosess kan føre til trekk.",
"Vi nyttar statistikksystem som køyrer dagleg anonym rapport. Personidentifiserande data vert fjerna før tal vert brukte til offentlege rapportar.",
"Gir du andre lesetilgang, kan dei sjå dokument, men ikkje endre. Skrivetilgang krev fullmakt, signert digitalt av både deg og den nye brukaren.",
"Instruksjonen «Utkast til orientering» betyr at sakshandsamar vil sjå dokumentet, men ikkje starte vurdering før alt er merka «Klar til gjennomgang».",
"Samla behandlingstid gjeld frå komplett innsending; manglande vedlegg stoppar klokka. Når siste dokument er registrert, startar tidsrekninga på nytt.",
"Når prosjektkode er allokert, kan du ikkje bytte tiltaksart utan at heile søknaden skrivast om. Kontakt rådgivar før du prøver å endre større felt.",
"Grunnlagsdata frå NAV vert henta kryptert. Feilar oppslag, får du melding «Trykk henta på nytt». Ved gjentakande feil må du kontakte NAV direkte.",
"Beløp under kroner femti vert ikkje utbetalt, men kan samlast opp til neste termin. Sjå saldooversikt i utbetalings­historikken for akkumulerte småbeløp.",
"Kvitterings-ID er unik per innsending. Dersom du sender fleire søknader same dag, får kvar søknad eiget ID-nummer til bruk i all vidare korrespondanse.",
"Utgått fullmakt vert automatisk fjerna, og representanten mister tilgang. Du får e-post tre dagar før utløp med lenkje for eventuell fornying.",
"Hugs å legge ved arbeidskontrakt dersom du søkjer stønad som sjølvstendig men samtidig har deltidsstilling. Systemet sjekkar for overlappande inntekt.",
"Når du har gjennomført digital identitetskontroll, vert statusen oppdatert til «Identitet verifisert». Merk at bankkonto må vere i same namn som søkar.",
"Etterkontroll kan skje opptil tre år etter utbetaling. Du pliktar å oppbevare bilag i heile denne perioden og syte for at dei er tilgjengelege ved førespurnad.",
"E-post frå systemet kan hamne i spamfilter. Dersom du ikkje ser kvittering eller varsel, legg til noreply-adressa i kontaktlista di for å hindre filtrering.",
"Hovudbokførsel må vere avstemt før endeleg rapport. Differanse mellom budsjett og faktisk kostnad skal forklarast i feltet «Avvikskommentar».",
"Ved fleirårige prosjekt skal statusrapport sendast årleg innan 31. mars. Uteblitt rapport fører til stans i vidare utbetalingar inntil saka er oppdatert.",
"Betalingspåminning vert sendt éin gong. Ubetalt krav går vidare til Statens innkrevjingssentral etter 14 dagar utan manuell purring frå vår side.",
"Du kan laste ned alle innsendte dokument som ZIP-arkiv. Arkivet er passordbeskytta med fødselsdatoen din som passord og gjeld i sytti timar frå generering.",
"Dersom du søkjer frå utlandet, vert IP-adressa registrert i historikken. Høgrisikolanda krev manuell godkjenning før innsending kan fullførast.",
"Filane dine vert skanna for skadelig kode. Ved funn av virus vert heile innsendinga avvist, og du må laste opp reine filer før vi kan gå vidare.",
"Søknadsperioden vert stengd kl. 23:59 siste fristdag. Systemet tek ikkje høgde for tidsforskjellar, så legg inn skjemaet i god tid om du er i annan tidssone.",
"Alle pengar vert utbetalte til konti i norsk bank. Dersom du oppgir utanlandsk konto, må IBAN og BIC registrerast, og behandlingstida vert forlen"
],
    long: [
    "Når forvaltninga mottek ein digital førespurnad om mellombels yting, blir datastrømmen først filtrert gjennom den sentrale valideringsmotoren, der obligatoriske felt vert sjekka mot folkeregister, arbeidsgivarregister og skatteetaten før systemet genererer ei kontrollsum; manglar det identitetsverdiar, hamnar saka i karantenestatus «Avvent dokumentasjon», og søkjaren får varsel via SMS og e-post med detaljert mangelrapport og frist på sju kalenderdagar, elles vert innsendinga annullert og må startast på nytt via personleg innlogging.",
    "I tilskotsordninga for innovasjon vert kvar tiande søknad valt ut til manuell stikkprøvekontroll, der saksbehandlar går gjennom hovudbok, bilag og kvitteringskjede; dersom avvik overstig tre prosent av budsjettert sum, vert heile prosjektet sett i «Høgrisiko» og konsekvensen kan bli delvis tilbakehald av utbetaling inntil styringsgruppa har motteke revidert dokumentasjon, nye kostnadsoverslag og signert stadfesting frå autorisert revisor om at dei nye tala er korrekte og fullstendige.",
    "Ved behandling av dispensasjon frå arealplan legg systemet automatisk inn nabovarselet i offentleg journal, men publiserer ikkje kartkoordinatar før manuell sladding av sensitive opplysningar er gjennomført; dersom partar sender inn merknader innan fristen på 14 dagar, startar ei ny runde med partsinnsyn, og ansvarleg saksbehandlar må oppdatere etterfølgande framdriftsplan i byggesakssystemet før endeleg vedtak vert lagt ut og klagefristen byrjar å løpe frå publiseringsdato.",
    "Når ein klage vert registrert mot eit tidlegare vedtak om stadfesta tvangsmulkt, må faginstansen innan fem arbeidsdagar utarbeide eit oversendingsbrev til klagenemnda som inneheld oppdatert faktagrunnlag, rettslege vurderingar og eventuelle tilståtte feil; klagenemnda kan velje å oppheve, endre eller stadfeste vedtaket, men dersom ny informasjon kjem til i klageprosessen, pliktar instansen å gjere om på eige initiativ før saka vert avgjort, slik forvaltningslova § 35 opnar for.",
    "I periodisk etterkontroll av utdanningsstønad kryss­refererer systemet automatisk studiepoeng mot nasjonal vitnemålsdatabase; finn det avvik mellom rapporterte og oppnådde resultat, genererast eit varselbrev som krev forklaring og eventuell tilbakebetaling innan 30 dagar; uteblir svar, kan saken sendast til Statens innkrevjingssentral, og utbetalingar vert stansa til dokumentert framdrift ligg føre og ny automatvalidering viser samsvar mellom oppgitt studieplan og reelle oppnådde einingar.",
    "Når to offentlege etatar skal dele datagrunnlag under paraplyen for samordna tenestetilbod, blir overføringa først kryptert ende-til-ende via statleg integrasjonsplattform; før oppkopling må begge databehandlarar signere standard datadelingsavtale med formålsspesifikk paragraf vise til § 13-5 i personopplysningsforskrifta, og kvar overføring loggast med tid, føremål og behandlingsgrunnlag; avvik rapporterast til personvernombodet og kan medføre mellombels sperre av API-tilgangen.",
    "I samband med utbetaling av kulturmidlar krev departementet prosjekt­rapport i PDF-format innan 60 dagar etter siste arrangement; rapporten må innehalde publikumstal, økonomisk oversikt og evaluering; dersom talet på billettar avviker meir enn ti prosent frå prognosen, triggar systemet automatisk krav om skriftleg forklaring, og utbetaling av siste rater vert sett i reserve­modus til forklaringa er godkjend av rådgjevande komité og attestert av fylkeskommunen som tilsynsmyndigheit.",
    "For fakturakrav som går til offentleg sektor gjeld 30-dagars betalingsfrist rekna frå korrekt mottatt EHF; dersom leverandøren manglar rekvisisjon, stoppar fakturaen i kontrollsteget «Attestasjonsvent» og rekvirent får varsel i intern arbeidsflyt; blir den ikkje komplettert innan to virkedagar, returnerer økonomisystemet fakturaen til avsendar med kode 903 «Manglande referanse», og ny faktura må sendast innan fem dagar for å unngå forseinkingsrente etter forsinkingsrentelova.",
    "Under revisjon av eigedomsskatt gjennomfører kommunen feltkontroll der laserskannerdata vert samanlikna med byggesøknadane; dersom volum av uregistrerte tilbygg overstig fem kvadratmeter, genererast automatisk varselbrev til eigar med melding om korreksjon; eigar får høve til å uttale seg innan fire veker, før fastsetjing av nytt skattegrunnlag; unnlat eigar å svare, vert taksten fastsett skjønnsmessig, og høve til klage er avgrensa til formfeil i prosedyren.",
    "I pilotprosjektet for digital velferdsteknologi integrerer kommunen sensorar frå tryggleiksalarmar med helsejournal­systemet; før data kan strøyme, må kvart produkt ha samsvarserklæring etter MDR og ETSI; informasjonen vert lagra i 72 timar for akutte varsel og deretter pseudonymisert for statistikk; brukaren og primærkontakt får varsel ved lågt batterinivå, men manglar dei respons innan oppsett responstid, opprettar vaktsentralen automatisk oppdrag til heimesjukepleia utan ekstra godkjenning.",
    "Ved årsoppgjeret for foreldrepengar kontrollerer systemet automatisk differansen mellom førehandsberekna grunnlag og innrapportert inntekt frå a-ordninga; overstig avviket fire prosent, vert eit varselbrev generert med førehandsutfylt kontonummer for eventuell tilbakebetaling; søkjar får ti arbeidsdagar til å sende korrigerande dokumentasjon, og dersom ny berekning stadfestar overutbetaling, set systemet opp avdragsplan over tolv månader, men gir høve til samstundes innbetaling for å unngå påløpande rente etter forsinkingsrentelova § 3.",
    "Når ein leverandør klagar på tildelingsvedtak i ein offentleg anbodskonkurranse, må innkjøpsseksjonen innan fem verkedagar utarbeide skjema KOFA-1, som inneheld fullstendig vurderingsmatrise, poengsummer og grunngjeving for valde vektingar; skjemaet vert sendt elektronisk til klagenemnda for offentlege anskaffingar og samtidig lagt i eInnsyn med sladd av forretningshemmelegheiter; dersom KOFA opnar sak, står avtaleinngåing på vent til rettskraftig avgjerd, og kommunen pliktar å rapportere status kvar trettiande dag.",
    "Før konsesjon for ny akvakulturlokalitet kan tildelast, gjennomfører miljødirektoratet ein tredelt rutine der vasskvalitetsdata, rømmingshistorikk og sonekart for lakselus vert kryssvaliderte mot søknaden; dersom berekningsmodellen viser fare for overskriding av maksimal biomasse, genererer systemet automatisk eit utkast til avslag med høyringsfrist på fjorten dagar; operatøren kan då leggje fram retta utleggingsplan og justert utsleppsprofil, og ny simulering må vise risiko under terskel før løyve kan innvilgast på vilkår om årleg miljørapport.",
    "Ved tryggleiksbrot der færre enn fem hundre brukarar er råka, pliktar eininga likevel å loggføre hendinga i intern avviksdatabase med konsekvensvurdering etter mal for påverknad på konfidensialitet, integritet og tilgjenge; risikoscoren vert rekna ut i sanntid, og overstig totalen 6,5, genererer systemet varsel til Datatilsynet innan 72 timar og til dei registrerte via standard brev; teknisk stab legg fram tiltaksplan, og personvernombodet signerer sluttattest når alle kompenserande tiltak er implementerte og verifiserte.",
    "I ordninga for vern av freda bygningar må søkjar sende inn detaljert restaureringsplan, inklusive materialspesifikasjonar og koloristisk dokumentasjon som stadfestar historisk fargepalett; fylkeskommunal rådgivar vurderer planen mot kulturminnelova § 15, og dersom moderne inngrep kan svekkje autentisiteten, får søkjar tjue dagar til revisjon; godkjend plan utløyser utbetaling i to ratar, den siste først etter sluttbefaring med protokoll signert av kulturvernavdelinga og rapport lagra i det digitale kulturminnearkivet Askeladden.",
    "Tilskot til øving for beredskapsavtalar vert utløyst når arrangøren har levert scenario­beskriving, ressursdisponering og etterspelsplan; systemet koplar søknaden til nasjonal øvingskalender for å unngå datokollisjon; krev øvinga deltaking frå politi eller helse, går automatiske varsel til fagetat med frist fem verkedagar til merknad; manglar godkjenning, set systemet status til «Klar, men på vent», og midlane vert ikkje utbetalte før alle involverte har stadfesta samtykke elektronisk.",
    "I energitilskotsprogramma for landbruk verifiserer systemet EPC-rapport frå sertifisert rådgivar mot Enova-databasen; overstig forventa reduksjon tjue prosent av baseline, kalkulerer motoren støtte etter sats per spart kilowattime; dersom samla tilskot går over to millionar kroner, krev regelverket tilleggsgodkjenning frå distriktsavdelinga; etter installasjon må bonden laste opp målar­data i seks månader, og berre ved dokumentert effekt over åttifem prosent utbetalast sluttoppgjer utan trekk.",
    "Grensependlarar med arbeid på begge sider av riksgrensa skal årleg sende inn samordningsskjema RF-1209; skatteetaten kryssjekkar dagtal i A1-attesten mot data frå svensk Skatteverket; overstig differansen fem arbeidsdagar, vert ytinga rekna om og differanseskatt fakturert; pendlaren får tre veker til å sende ny dokumentasjon, og dersom perioden ikkje kan stadfestast, vert skattetrekk sett til maksimal sats til korrekt informasjon ligg føre i systemet.",
    "Etter ekstremveret kan jordbruks­føretak søkje erstatning for avlingstap gjennom ROS-modulen; satellittdata frå Copernicus måler NDVI før og etter hendinga og gir førebels tapsscore; landbrukskontoret verifiserer med synfaring, og dersom avviket ligg innan fem prosent, utbetalast erstatninga etter normtabell; større avvik utløyser ny runde der føretaket må sende foto og dataloggar frå klimastasjonane, og systemet stansar utbetaling til data er verifiserte.",
    "Ved mellombels stenging av fylkesveg grunna asfaltarbeid nyttar trafikkseksjonen digital arbeidsordre som synkroniserer med Vegtrafikksentralen; systemet publiserer varsling på 175.no, sender pushmelding til navigasjons-API og oppdaterer variable leiskilt; entreprenøren registrerer oppstart og ferdigmelding via app som loggar GPS-spor og tidsstempel; forseinking over tretti minutt genererer varsel til byggherre og politi, og manglande registrering kan medføre dagsmulkter og redusert modulscore i framtidige anbod.",
    "Når etterkontroll av økonomisk sosialhjelp vert iverksett, kryssrefererer saks­systemet alle utbetalingar mot betalingslogg frå NAV, Skatteetaten og Husbanken; syner oppslaget at stønad er motteken samstundes frå fleire ordningar, fløymer grunnlag til kontrollmotoren som kalkulerer sum av potensielt feilutbetalt beløp; overstig totalen éin G, blir det per automatikk oppretta ei varslingssak med status «Mogleg tilbakesøk» og det genererast førehandsvarsel til mottakaren med 14-dagars tilsvarsfrist, der det vert gjort greie for rett til innsyn, klage og eventuelt høve til nedbetalingsavtale før saka vert oversend til innkrevjingseininga dersom svar uteblir eller dokumentasjonen ikkje endrar faktagrunnlaget vesentleg.",
    "I den statlege skymigrerings­strategien skal kvart direktorat kvart halvår levere attest på at underliggjande løysingar er sikkerheitskopierte i tre separate geosonar; attesten må vera signert av både system­ansvarleg og intern sikkerheitsrådgivar, og lastast opp gjennom e-Tjenesteportalen innan 5. april og 5. oktober; dersom filen manglar gyldig SHA-256-hash, returnerer portalen dokumentet som «Korrupt vedlegg», og verksemda får to verkedagar til å rette; unnlèt dei å levere innan utvida frist, vert status sett til «Rød» i styringskartet som rapporterast til Digitaliserings­direktoratet, og vidare tiltaksplan må godkjennast av departementet før verksemda får starte nye skyprosjekt.",
    "Museum som har motteke prosjektmidlar over kapittel 320, post 70, skal innan 31. desember same år sende inn revidert rekneskap på NS 4102-format med notefelt for kvar delaktivitet; systemet sjekkar først at kostnadsføringa samsvarer med budsjettlinjene i søknaden og at eigenandel er bokført på rett art; viser differansen meir enn 15 % på nokon linje, får museet status «Avvik høg» og må innan 20 dager levere ny forklaring, justert framdriftsplan samt styreprotokoll — signert som digital PDF — som stadfestar at styret er varsla; først når kulturdepartementet har attestert rapporten, vert siste 20 % av løyvinga fristilt til utbetaling gjennom stats­rekneskapen.",
    "Kommunalt vassverk har innført fjernavlesing via NB-IoT-sensorar; kvar gong målaren sender datapakke, vert volum­verdiane sjekka mot forventingskurve generert frå historiske døgnverdiar, og dersom avviket overskrid 30 % i tre påfølgjande timar, opprettar systemet automatisk «Leakk-alarm» som går til beredskapsvakt; brukaren får parallelt SMS, og portalen låser fakturagrunnlaget til alarmen er lukka; viss lekkasjen vert verifisert som eigars ansvar, kan justert vass-avgift krevjast, men berre dersom foto­dokumentasjon av reparert leidning vert lasta opp innan 60 dagar og validerast av saksbehandlar i henhald til § 7-3 i lokal forskrift.",
    "Ved forlenging av arbeidsavklarings­pengar må samtykke til deling av helse­opplysningar fornyast; systemet sender varsel to veker før samtykket går ut, og dersom brukar ikkje signerer digitalt innan fristen, vert saka sett i pausemodus, medan behandlar får e-post om manglande grunnlag; arbeidsgivar kan ikkje sjå medisinske detaljar, men mottar statuskode «AA-Avklaring stansa» i Altinn; når nytt samtykke ligg føre, opnar systemet automatisert flyt, hentar forlengingsrapport frå lege via helsenettet og rekalkulerer ytinga med ny dato; tek det meir enn 30 dagar, blir det utløyst manuell saksbehandling og mogleg økonomisk oppgjer for avbrot.",
    "Havnevesenet sin sensorbaserte kaiavgift registrerer skipstrafikk ved anløp gjennom AIS-data og 3D-kamera; etter leggetid blir bruttotonnasjen multiplisert med gjeldande sats og faktura sendt elektronisk i EHF; karakteriserer sensoravlesinga skipet som offshore-støtteeining, blir miljørabatt ikke lagt til, og reiar får melding i kundesenteret; dersom kameraet feiltolkar fartøytypen, kan reiar innan 48 timar laste opp bevis på klassifikasjon, og systemet startar tvungen omberekning; manglande innsending gjer vedtaket endeleg og eventuelle gebyr må innbetalast før ny anløpstillatelse kan gis.",
    "I ordninga for digitalt skulebevis til studenttransport sjekkar modulen først at utdanningsinstitusjonen er registrert i DBH, deretter krypterer han person­data og legg qr-kode på beviset; transportørane får tilgang til validerings-API som returnerer status «Gyldig», «Avslått» eller «Utgått»; misbruk blir loggført, og minst tre avviste forsøk på ein dag fører til automatisk sperring av qr-koden; studenten varsles via e-post og må opprette sak i portalen; etter kontroll av semesteravgift kan sperringa opphevast av administrasjonen, og historikken vert lagra for datatilsyns­rapportering.",
    "Kartverket krev at landmålarar sender inn matrikkelmelding for kvart fullført oppmålingsforretning; meldinga må signeres med virksomhets­sertifikat og innehalde GML-fil, PDF-diagram og liste over nabovarsel; mottakarserveren kontrollerer at polygondata ikkje overlappar eksisterande grenser, og finn systemet konflikt i meir enn 0,5 meter, set han melding i «Avslag – Avvik geometri» og returnerer feilkoden til landmålar; retting må skje innan 15 dagar, elles vert ny gebyrsats utløyst; når meldinga vert godkjend, oppdaterast matrikkelen og eigar får automatisk tinglysings­brev i Altinn.",
    "For alle anbod over EØS-terskelverdien krev klimatiltaks­programmet at oppdragsgivar legg inn grønt kriteriesett i KGV-systemet; systemet sjekkar at delkriterium for utslepp og sirkularitet er vekta minimum 30 %; dersom krav ikkje er oppfylt, blokkerer det for publisering i Doffin og sender varsel til innkjøpsleiar; i evaluerings­fasen må vinnande leverandør fylle ut CO₂-kalkulator som vert signert elektronisk og publisert på ope data-portal; manglande innsending før kontrakts-signering får automatisert rettsvern-merknad som kan føre til KOFA-klage og mellombels avtale­stopp.",
    "Når eit statleg organ deponerar arkiv til Norsk eArkiv, vert det generert ein SIP-pakke med AIP-metadata, hash og DSig-fil; overførsla går over NSM-godkjent linje, og eArkiv kontrollerer at PREMIS-spor er korrekte; dersom pakkestrukturen bryt EU-profil for MoReq, blir deponering avvist med feilrapport; avsendar har fjorten dagar til å rekonstruere pakka utan å miste deponeringsslot-tid; etter vellukka validering kvitterer eArkiv med DIP til arkivverket og journalpost vert automatisk oppdatert med NASJONAL-ID som referanse; frå dette tidspunktet er materialet avlevert og kan ikkje slettast utan heimel i arkivlova § 12.",
    "Når fylkeskommunen gir lånegaranti til kollektivsamband, krev regelverket først ordinær likviditetsanalyse i finansmodulen; systemet hentar driftsdata frå billettsystemet, prognose frå transportetatens trafikkmodell og kontrollerer at dekninggrad er minst 1,05; er krava oppfylte, sender modulen automatisk ut høringsbrev til kommunane med 14-dagars svarfrist; manglar innvendingar, verte garanti­vedtak eksportert til Treasurysystemet som genererer garantikrav i statskassa; vedtaket blir ført i elektronisk garantiregister og oppdatert i eBehandling slik at revisor kan verifisere transaksjon og premieberrekning i årsoppgjeret utan manuelle steg.",
    "Digital tinglysing av eigedoms­overdraging startar med at meglar legg inn oppgjer i Portalen for eigedomsinformasjon; systemet krysskontrollerer matrikkeldata, heftelser og pantedokument, og krev tofaktor­signering frå alle partar via BankID; når siste signatur er logga, blir ettersynsmodulen i Kartverket varsla; finn den avvik i koord-kanal, setjast status til «Avvent korrektur» og meglar får 24 timar til å rette; ved godkjenning vert grunnboksblad automatisk oppdatert, kjøpar får PDF-kvittering, skattemeldinga får forhandsutfylt eigedomspost, og kommunen får grunnlag for ny eigedomsskatt utan manuell melding.",
    "I barnehage­opptaket kontrollerer kommunen søknadene gjennom integrert reglar­motor som sjekkar fødselsdato, prioritet og bustadadresse mot folkeregisteret; dersom to søkjarar konkurrerer om siste plass og har identiske poeng, genererast varsel til oppvekst­sjefen som må vurdere søskenmoderasjon eller dokumentert særskilt behov; handsamast ikkje konflikten innan tre døgn, vel systemet automatisk eldste barn; vedtak, eventuelt avslag, blir distribuert med trygg e-post og status «Lukka», men foreldre kan klage innan 21 dagar, deretter får formannskapet saka på digitalt møte under sakskode BHO-Klage-24.",
    "Skogeigarar som bruker skogfond, må rapportere planteaktivitet i Altinn-skjemaet «Landbruk 123»; modulen hentar automatisk GPS-spor frå hogstmaskin, og kontrollsjekkar at plantetetthet stemmer med innkjøpt frømateriale; er avvik over 10 %, får eigar melding om justert fondsskatt og krav om tilleggsdokumentasjon, til dømes faktura og fotobevis; blir ikkje dokumentasjon lasta opp innan 30 dagar, set systemet vedtaket til «Avvist» og krev tilbakebetaling av det lyfte fonds-forskotet med forsinkingsrente rekna frå opprinneleg utbetalingsdato.",
    "I ordninga med variabel miljøfartsgrense tar trafikkstyrings­systemet gjennomsnittleg NO₂-måling frå tre stasjonar og bereknar ut frå meteorolog­varsel om grense­verdien vil bli broten neste seks timar; dersom prognosen er kritisk, senkar motoren fartsgrensa automatisk i sanntids­skiltinga og sender data til politi-ANPR-systemet som skannar nummerplater; dei som køyrer over ny grense, får vedtaksbrev generert utan manuell handsaming; betaling kan gjerast via e-Faktura, og manglande betaling går til Statens innkrevjing etter 42 dagar.",
    "Arbeidstilsynet nyttar tilsynsmodul som rangerer verksemder etter risikoscore samansett av bransje, skadefrekvens og avvik frå HMS-rapportering; overstig score 8,0, ligg verksemda i prioritet for feltkontroll og vert automatisk tildelt ein inspektør; systemet sender varsel tre dagar før tilsyn, med lenkje til digital eigendeklarasjon; inspektøren loggfører funn på nettbrett som synkroniserer til hendingslogg; pålegg og tvangsmulkt vert rekna ut automatisk og sendt via Altinn, og verksemd må lukke avvik innan tidsfrist for å unngå dagbøter.",
    "Når forskings­prosjekt søkjer tilgang til sensitive helsedata gjennom Helseanalyse-plattformen, sjekkar autorisasjons­motoren at prosjektet har REK-godkjenning, data­behandlaravtale og oppdatert risikovurdering; etter godkjenning får prosjektleiar tidsavgrensa token som gir tilgang til pseudonymiserte data­sett; kvar spørring loggast og vert lagra i 10 år; oppdagar systemet uttrekk som kan re-identifisere individ, stoppar spørjinga og varslar personvernombodet; forskar får melding om å innsnevra filter og ny evaluering må til før hovudtoken aktiverast på nytt.",
    "Kompensasjons­ordninga for kultur­arrangement krev at arrangøren rapporterer billett­inntekt, refundert verdi og faktisk deltakartal; systemet hentar referansepris frå historisk omsetning i TicketCo eller tilsvarande billettsystem; overstig søknadsbeløpet 90 % av referanse­inntekta, flaggar motoren søknaden som «Kun manuell vurdering» og stansar automatikk; revisorrapport må leggjast ved som signert PDF før saksbehandlar kan opne utbetalings­knappen, og Noreg digital kultur­register blir oppdatert når vedtaket er endeleg.",
    "Lånekassen sin integrasjon mot ID-porten gjennomfører risk-analyse kvar sjette time; ser den unormal geografisk spreiing av påloggingar til same studentkonto, vert det sendt push-varsel og kontoen sett i totrinns tvungen modus; studenten må verifisere ansikt via app eller møte på campus-skranke; handsamast ikkje innan 14 dagar, vert ny utbetaling halde tilbake; når identitet er stadfesta, frigjer systemet betaling og legg sikkerheits­hendingslogg i e-postarkivet med 12-månaders lagringskrav.",
    "Forsvars­sektoren sin portal for sivil-militært samarbeid registrerer rekvisisjonar frå kommunar under kriseøving; kvar rekvisisjon vert sjekka mot nasjonalt beredskaps­lager og mot avtalt kompenserings­modell; overstig den forespurte ressursen definert terskel, går automatisk eskalering til operativ stab; godkjent rekvisisjon får status «Grønn» og kommunen mottar logistikkliste, mens avvist rekvisisjon blir sett «Raud» med påkravd kommunenummer; alle transaksjonar signeres med tidsstempel og lagrast i Militært arkivsystem for etterkontroll og historikk."
    ]
};
